import { useEffect, useState } from "react";
import { Bell, Check, Mail, MessageSquare, Smartphone } from "lucide-react";
import { useAuth } from "../../contexts/AuthContext";
import { defaultNotificationPreferences, getNotificationPreferences, saveNotificationPreferences, type NotificationPreferences } from "../../services/NotificationPreferencesService";
import { registerPushDevice } from "../../services/PushNotificationService";

const channels: { key: keyof NotificationPreferences; label: string; detail: string; icon: typeof Bell }[] = [
  { key: "inApp", label: "In-app notifications", detail: "Show alerts inside ASTEM.", icon: Bell }, { key: "push", label: "Push notifications", detail: "Receive alerts on supported devices.", icon: Smartphone }, { key: "email", label: "Email notifications", detail: "Send important alerts to your account email.", icon: Mail }, { key: "sms", label: "SMS notifications", detail: "Reserve urgent alerts for SMS delivery.", icon: MessageSquare },
];

export default function NotificationPreferencesPage() {
  const { user } = useAuth(); const [preferences, setPreferences] = useState(defaultNotificationPreferences); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  useEffect(() => { if (!user) return; getNotificationPreferences(user.uid).then(setPreferences).catch(loadError => setError(loadError instanceof Error ? loadError.message : "Unable to load preferences.")).finally(() => setLoading(false)); }, [user]);
  const save = async () => { if (!user) return; setSaving(true); setError(""); try { await saveNotificationPreferences(user.uid, preferences); setMessage("Notification preferences saved."); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "Unable to save preferences."); } finally { setSaving(false); } };
  const enablePush = async () => { if (!user) return; setSaving(true); setError(""); try { await registerPushDevice(user.uid); const next = { ...preferences, push: true }; setPreferences(next); await saveNotificationPreferences(user.uid, next); setMessage("Push notifications enabled on this device."); } catch (pushError) { setError(pushError instanceof Error ? pushError.message : "Unable to enable push notifications."); } finally { setSaving(false); } };
  return <div className="mx-auto max-w-3xl space-y-6"><div><p className="text-sm font-semibold uppercase tracking-wider text-primary">Account settings</p><h1 className="mt-1 text-3xl font-bold text-slate-900">Notification delivery</h1><p className="mt-2 text-sm text-slate-500">Choose where school alerts should be delivered.</p></div>{message && <div className="rounded-lg bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-700">{message}</div>}{error && <div className="rounded-lg bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}<section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="divide-y divide-slate-100">{channels.map(({ key, label, detail, icon: Icon }) => <label key={key} className="flex cursor-pointer items-center justify-between gap-4 py-4"><div className="flex items-center gap-3"><div className="rounded-lg bg-primary p-2 text-primary"><Icon size={19} /></div><div><p className="text-sm font-semibold text-slate-800">{label}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></div></div><input type="checkbox" checked={preferences[key]} disabled={loading} onChange={event => setPreferences({ ...preferences, [key]: event.target.checked })} className="h-5 w-5 accent-primary" /></label>)}</div><div className="mt-5 flex items-start gap-2 rounded-lg bg-slate-50 p-3 text-xs leading-5 text-slate-500"><Check size={16} className="mt-0.5 shrink-0 text-emerald-600" />Push requires browser permission and a configured Firebase VAPID key.</div><div className="mt-5 flex flex-wrap gap-2"><button onClick={() => void save()} disabled={saving || loading} className="rounded-lg bg-primary px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{saving ? "Saving..." : "Save preferences"}</button><button type="button" onClick={() => void enablePush()} disabled={saving || loading || preferences.push} className="rounded-lg border border-primary px-5 py-2.5 text-sm font-semibold text-primary disabled:opacity-50">{preferences.push ? "Push enabled" : "Enable push on this device"}</button></div></section></div>;
}
