import type { RekognitionClient } from "@aws-sdk/client-rekognition";
import { FieldValue, getFirestore } from "firebase-admin/firestore";
import { HttpsError, onCall } from "firebase-functions/v2/https";
import { defineSecret, defineString } from "firebase-functions/params";
const accessKey = defineSecret("AWS_ACCESS_KEY_ID"); const secretKey = defineSecret("AWS_SECRET_ACCESS_KEY"); const region = defineString("AWS_REKOGNITION_REGION", { default: "us-east-1" }); const collectionId = defineString("AWS_REKOGNITION_COLLECTION_ID", { default: "astem-ssm-attendance-prod" }); const threshold = defineString("AWS_FACE_MATCH_THRESHOLD", { default: "95" });
let cached: RekognitionClient | undefined;
async function client() { if (!cached) { const { RekognitionClient } = await import("@aws-sdk/client-rekognition"); cached = new RekognitionClient({ region: region.value(), credentials: { accessKeyId: accessKey.value(), secretAccessKey: secretKey.value() } }); } return cached; }
async function userId(request: any) { if (!request.auth) throw new HttpsError("unauthenticated", "Sign in is required."); if (!(await getFirestore().collection("users").doc(request.auth.uid).get()).exists) throw new HttpsError("permission-denied", "User profile is not configured."); return request.auth.uid; }
async function validateSchoolId(schoolId: string) { const firestore = getFirestore(); const [student, staff] = await Promise.all([firestore.collection("students").where("studentId", "==", schoolId).limit(1).get(), firestore.collection("teachers").where("teacherId", "==", schoolId).limit(1).get()]); if (student.empty && staff.empty) throw new HttpsError("not-found", "The school ID does not belong to a student or staff profile."); }
export const verifyAttendanceFace = onCall({ region: "africa-south1", secrets: [accessKey, secretKey] }, async request => { const uid = await userId(request); const schoolId = String(request.data?.schoolId || "").trim(); const imageBytes = String(request.data?.imageBytes || ""); if (!schoolId || !imageBytes) throw new HttpsError("invalid-argument", "schoolId and imageBytes are required."); const { SearchFacesByImageCommand } = await import("@aws-sdk/client-rekognition"); const result = await (await client()).send(new SearchFacesByImageCommand({ CollectionId: collectionId.value(), Image: { Bytes: Buffer.from(imageBytes, "base64") }, FaceMatchThreshold: Number(threshold.value()), MaxFaces: 3, QualityFilter: "AUTO" })); const match = result.FaceMatches?.find(item => String(item.Face?.ExternalImageId || "") === schoolId); const confidence = Number(match?.Similarity || 0); const passed = Boolean(match && confidence >= Number(threshold.value())); await getFirestore().collection("attendanceFaceVerifications").add({ userId: uid, schoolId, passed, matchConfidence: confidence, faceId: match?.Face?.FaceId || null, verificationMethod: "rekognition-face-match", createdAt: FieldValue.serverTimestamp() }); if (!passed) throw new HttpsError("permission-denied", "Face does not match the enrolled school identity."); return { passed, schoolId, matchConfidence: confidence, verificationMethod: "rekognition-face-match" }; });
export const enrollAttendanceFace = onCall({ region: "africa-south1", secrets: [accessKey, secretKey] }, async request => { const uid = await userId(request); const profile = await getFirestore().collection("users").doc(uid).get(); if (!["admin", "superadmin"].includes(String(profile.data()?.role || "").toLowerCase())) throw new HttpsError("permission-denied", "Administrator access is required."); const schoolId = String(request.data?.schoolId || "").trim(); const imageBytes = String(request.data?.imageBytes || ""); if (!schoolId || !imageBytes) throw new HttpsError("invalid-argument", "schoolId and imageBytes are required."); await validateSchoolId(schoolId); const { IndexFacesCommand } = await import("@aws-sdk/client-rekognition"); const result = await (await client()).send(new IndexFacesCommand({ CollectionId: collectionId.value(), Image: { Bytes: Buffer.from(imageBytes, "base64") }, ExternalImageId: schoolId, MaxFaces: 1, QualityFilter: "AUTO" })); const face = result.FaceRecords?.[0]?.Face; if (!face?.FaceId) throw new HttpsError("invalid-argument", "No usable face was detected."); await getFirestore().collection("attendanceFaceEnrollments").doc(schoolId).set({ schoolId, faceId: face.FaceId, enrolledBy: uid, enrolledAt: FieldValue.serverTimestamp() }, { merge: true }); return { schoolId, faceId: face.FaceId }; });
