import { useEffect, useState } from "react";
import { Printer, ReceiptText } from "lucide-react";
import { collection, getDocs, query, where } from "firebase/firestore";
import { useAuth } from "../../contexts/AuthContext";
import { db } from "../../firebaseConfig";

type Payslip = { id: string; period: string; staffName: string; grossSalary: number; deductions: number; netSalary: number; status: string };
export default function StaffPayslipsPage() { const { user } = useAuth(); const [items, setItems] = useState<Payslip[]>([]); useEffect(() => { if (!user?.uid) return; getDocs(query(collection(db, "staffPayroll"), where("staffId", "==", user.uid), where("status", "in", ["approved", "paid"]))).then((snapshot) => setItems(snapshot.docs.map((item) => ({ id: item.id, ...item.data() })) as Payslip[])).catch(console.warn); }, [user?.uid]); return <main className="mx-auto max-w-5xl space-y-6"><header><p className="text-sm font-semibold uppercase tracking-wider text-indigo-600">Staff services</p><h1 className="mt-1 text-3xl font-bold text-slate-900">Payslips</h1><p className="mt-1 text-sm text-slate-500">Print or save your approved payroll records for your personal files.</p></header>{items.map((item) => <article key={item.id} className="rounded-xl border border-slate-200 bg-white p-6"><div className="flex items-start justify-between"><div><div className="flex items-center gap-2 text-indigo-600"><ReceiptText size={20} /><span className="text-xs font-bold uppercase tracking-wider">ASTEM-SSM</span></div><h2 className="mt-3 text-xl font-bold text-slate-900">Staff payslip · {item.period}</h2><p className="mt-1 text-sm text-slate-500">{item.staffName}</p></div><button onClick={() => window.print()} className="inline-flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-sm font-semibold text-slate-700"><Printer size={16} /> Print / PDF</button></div><div className="mt-6 grid gap-3 border-t border-slate-100 pt-5 sm:grid-cols-3"><Amount label="Gross salary" value={item.grossSalary} /><Amount label="Deductions" value={item.deductions} /><Amount label="Net pay" value={item.netSalary} /></div><p className="mt-5 text-xs capitalize text-slate-500">Status: {item.status}</p></article>)}{!items.length && <p className="rounded-xl border border-slate-200 bg-white p-8 text-center text-sm text-slate-500">No approved payslips are available.</p>}</main>; }
function Amount({ label, value }: { label: string; value: number }) { return <div className="rounded-lg bg-slate-50 p-4"><p className="text-xs uppercase text-slate-500">{label}</p><p className="mt-2 text-lg font-bold text-slate-900">GHS {value.toFixed(2)}</p></div>; }
