import { useEffect, useState } from "react";
import { Banknote, HeartHandshake, Landmark } from "lucide-react";
import { useAuth } from "../../contexts/AuthContext";
import { db } from "../../firebaseConfig";
import { collection, getDocs, query, where } from "firebase/firestore";

type RecordItem = { id: string; staffId: string; staffName: string; status: string; period?: string; netSalary?: number; balance?: number; amount?: number; type?: string; notes?: string };
export default function StaffFinancePage() { const { user } = useAuth(); const [payroll, setPayroll] = useState<RecordItem[]>([]); const [loans, setLoans] = useState<RecordItem[]>([]); const [welfare, setWelfare] = useState<RecordItem[]>([]); const [error, setError] = useState(""); useEffect(() => { if (!user?.uid) return; Promise.all([getDocs(query(collection(db, "staffPayroll"), where("staffId", "==", user.uid))), getDocs(query(collection(db, "staffLoans"), where("staffId", "==", user.uid))), getDocs(query(collection(db, "staffWelfare"), where("staffId", "==", user.uid)))]).then(([p, l, w]) => { setPayroll(p.docs.map((item) => ({ id: item.id, ...item.data() })) as RecordItem[]); setLoans(l.docs.map((item) => ({ id: item.id, ...item.data() })) as RecordItem[]); setWelfare(w.docs.map((item) => ({ id: item.id, ...item.data() })) as RecordItem[]); }).catch(() => setError("Unable to load your financial records.")); }, [user?.uid]); return <main className="mx-auto max-w-6xl space-y-6"><header><p className="text-sm font-semibold uppercase tracking-wider text-indigo-600">Staff services</p><h1 className="mt-1 text-3xl font-bold text-slate-900">My financial records</h1><p className="mt-1 text-sm text-slate-500">Review your approved payroll, loan balance, and welfare history.</p></header>{error && <p className="rounded-lg bg-red-50 p-4 text-sm text-red-700">{error}</p>}<div className="grid gap-6 lg:grid-cols-3"><RecordCard title="Payslips" icon={<Banknote />} items={payroll} value={(item) => `GHS ${(item.netSalary || 0).toFixed(2)} · ${item.period || "Period"}`} /><RecordCard title="Loans" icon={<Landmark />} items={loans} value={(item) => `Balance GHS ${(item.balance || 0).toFixed(2)} · ${item.status}`} /><RecordCard title="Welfare" icon={<HeartHandshake />} items={welfare} value={(item) => `GHS ${(item.amount || 0).toFixed(2)} · ${item.type || "record"}`} /></div></main>; }
function RecordCard({ title, icon, items, value }: { title: string; icon: React.ReactNode; items: RecordItem[]; value: (item: RecordItem) => string }) { return <section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="flex items-center gap-2 font-semibold text-slate-900"><span className="text-indigo-600">{icon}</span>{title}</h2>{items.map((item) => <div key={item.id} className="mt-4 rounded-lg border border-slate-100 bg-slate-50 p-3"><p className="text-sm font-semibold text-slate-800">{value(item)}</p><p className="mt-1 text-xs capitalize text-slate-500">Status: {item.status}</p></div>)}{!items.length && <p className="mt-4 text-sm text-slate-500">No records available.</p>}</section>; }
