import { useEffect, useState } from "react";
import { BookOpen, CalendarClock, CheckCircle2, CircleAlert } from "lucide-react";
import { useAuth } from "../../contexts/AuthContext";
import { fetchUserLibraryLoans, type LibraryLoan } from "../../services/LibraryService";

export default function LibraryRecordsPage() {
  const { user } = useAuth();
  const [loans, setLoans] = useState<LibraryLoan[]>([]);
  useEffect(() => { if (user?.uid) fetchUserLibraryLoans(user.uid).then(setLoans).catch(console.warn); }, [user?.uid]);
  return <main className="min-h-screen bg-slate-50 p-4 md:p-8"><div className="mx-auto max-w-5xl space-y-6"><header><p className="text-sm font-semibold uppercase tracking-wider text-primary">Student services</p><h1 className="mt-1 text-3xl font-bold text-slate-900">My library records</h1><p className="mt-1 text-sm text-slate-500">Keep track of books currently borrowed and return dates.</p></header><section className="grid gap-4 sm:grid-cols-3"><div className="rounded-xl border border-slate-200 bg-white p-4"><BookOpen className="text-primary" /><p className="mt-3 text-2xl font-bold">{loans.filter((l) => l.status !== "returned").length}</p><p className="text-sm text-slate-500">Active loans</p></div><div className="rounded-xl border border-amber-200 bg-amber-50 p-4"><CircleAlert className="text-amber-600" /><p className="mt-3 text-2xl font-bold">{loans.filter((l) => l.status === "overdue").length}</p><p className="text-sm text-amber-800">Overdue</p></div><div className="rounded-xl border border-slate-200 bg-white p-4"><CheckCircle2 className="text-emerald-600" /><p className="mt-3 text-2xl font-bold">{loans.filter((l) => l.status === "returned").length}</p><p className="text-sm text-slate-500">Returned</p></div></section><section className="divide-y divide-slate-100 rounded-xl border border-slate-200 bg-white">{loans.map((loan) => <div key={loan.id} className="flex items-center justify-between gap-4 p-5"><div><p className="font-semibold text-slate-900">{loan.bookTitle}</p><p className="mt-1 flex items-center gap-1 text-sm text-slate-500"><CalendarClock size={15} /> Due {loan.dueDate}</p></div><span className={`rounded-full px-3 py-1 text-xs font-semibold ${loan.status === "overdue" ? "bg-rose-100 text-rose-700" : loan.status === "returned" ? "bg-slate-100 text-slate-600" : "bg-amber-100 text-amber-700"}`}>{loan.status}</span></div>)}{!loans.length && <p className="p-10 text-center text-sm text-slate-500">No library records found.</p>}</section></div></main>;
}
