import { useCallback, useEffect, useState } from "react";
import { Pressable, Text, TextInput, View } from "react-native";
import { AdminPageShell } from "../../src/components/AdminPageShell";
import { StudentDataState } from "../../src/components/StudentDataState";
import { useAuth } from "../../src/contexts/AuthContext";
import { useSync } from "../../src/contexts/SyncContext";
import { communicationDocumentId, fetchAdminCommunications, type AdminCommunicationData, type Audience, type CommunicationCategory } from "../../src/services/adminCommunicationService";

const audiences: Audience[] = ["all", "admin", "teacher", "student", "parent"];
const categories: CommunicationCategory[] = ["announcement", "info", "alert"];

export default function AdminAnnouncementsPage() {
  const { user } = useAuth(); const { queueWrite } = useSync();
  const [data, setData] = useState<AdminCommunicationData | null>(null); const [title, setTitle] = useState(""); const [messageText, setMessageText] = useState(""); const [audience, setAudience] = useState<Audience>("all"); const [category, setCategory] = useState<CommunicationCategory>("announcement"); const [published, setPublished] = useState(true);
  const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false); const [offline, setOffline] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { if (!user) return; setLoading(true); setError(""); try { const result = await fetchAdminCommunications(user.uid); setData(result); setOffline(result.source === "cache"); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Unable to load announcements."); } finally { setLoading(false); } }, [user]);
  useEffect(() => { void load(); }, [load]);
  const create = async () => { if (!title.trim() || !messageText.trim()) return setError("Enter a title and message."); setSaving(true); setError(""); try { const id = communicationDocumentId("ANN"); const result = await queueWrite({ path: `schoolAnnouncements/${id}`, type: "set", merge: false, serverTimestampFields: ["createdAt"], data: { title: title.trim(), message: messageText.trim(), audience, category, published, createdBy: user?.uid || "" } }); setTitle(""); setMessageText(""); setNotice(result === "synced" ? "Announcement saved." : "Announcement saved offline and queued."); await load(); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "Unable to save announcement."); } finally { setSaving(false); } };
  const remove = async (id: string) => { setSaving(true); try { const result = await queueWrite({ path: `schoolAnnouncements/${id}`, type: "delete" }); setNotice(result === "synced" ? "Announcement removed." : "Removal queued."); await load(); } finally { setSaving(false); } };
  return <AdminPageShell subtitle="Publish notices, alerts, and draft announcements for school audiences." title="Announcements"><StudentDataState error={error} loading={loading} offline={offline} onRefresh={load} />{!!notice && <Text className="mt-4 rounded-2xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">{notice}</Text>}<View className="mt-5 rounded-3xl bg-white p-5"><Text className="text-lg font-extrabold text-slate-900">New announcement</Text><TextInput className="mt-3 rounded-2xl bg-slate-50 px-4 py-4 text-base" onChangeText={setTitle} placeholder="Title" placeholderTextColor="#94a3b8" value={title} /><TextInput className="mt-3 min-h-28 rounded-2xl bg-slate-50 px-4 py-4 text-base" multiline onChangeText={setMessageText} placeholder="Message" placeholderTextColor="#94a3b8" textAlignVertical="top" value={messageText} /><ChoiceRow options={audiences} selected={audience} setSelected={(value) => setAudience(value as Audience)} /><ChoiceRow options={categories} selected={category} setSelected={(value) => setCategory(value as CommunicationCategory)} /><Pressable className={`mt-1 rounded-full px-4 py-3 ${published ? "bg-emerald-100" : "bg-slate-100"}`} onPress={() => setPublished(!published)}><Text className={`text-sm font-bold ${published ? "text-emerald-800" : "text-slate-700"}`}>{published ? "Publish immediately" : "Save as draft"}</Text></Pressable><SaveButton label="Save announcement" saving={saving} onPress={create} /></View><View className="mt-5">{data?.announcements.map((item) => <Card key={item.id} title={item.title} meta={`${item.audience} | ${item.category} | ${item.published ? "published" : "draft"}`} body={item.message} pending={item.pending} remove={() => remove(item.id)} saving={saving} />)}</View></AdminPageShell>;
}

function ChoiceRow({ options, selected, setSelected }: { options: readonly string[]; selected: string; setSelected: (value: string) => void }) { return <View className="mt-3 flex-row flex-wrap">{options.map((item) => <Pressable className={`mb-2 mr-2 rounded-full px-3 py-3 ${selected === item ? "bg-indigo-700" : "bg-slate-100"}`} key={item} onPress={() => setSelected(item)}><Text className={`text-xs font-bold capitalize ${selected === item ? "text-white" : "text-slate-700"}`}>{item}</Text></Pressable>)}</View>; }
function SaveButton({ label, saving, onPress }: { label: string; saving: boolean; onPress: () => void }) { return <Pressable className="mt-3 items-center rounded-2xl bg-indigo-700 px-4 py-4" disabled={saving} onPress={onPress}><Text className="text-sm font-bold text-white">{saving ? "Saving..." : label}</Text></Pressable>; }
function Card({ title, meta, body, pending, remove, saving }: { title: string; meta: string; body: string; pending: boolean; remove: () => void; saving: boolean }) { return <View className="mb-3 rounded-3xl bg-white p-5"><Text className="text-lg font-extrabold text-slate-900">{title}</Text><Text className="mt-1 text-xs uppercase text-slate-500">{meta}</Text><Text className="mt-3 text-sm leading-6 text-slate-600">{body}</Text>{pending ? <Text className="mt-3 text-xs font-bold uppercase text-amber-700">Queued</Text> : <Pressable className="mt-4 items-center rounded-2xl bg-red-50 px-4 py-3" disabled={saving} onPress={remove}><Text className="text-sm font-bold text-red-700">Remove</Text></Pressable>}</View>; }
