import { useCallback, useEffect, useState } from "react";
import { Pressable, Text, TextInput, View } from "react-native";
import { AdminPageShell } from "../../src/components/AdminPageShell";
import { StudentDataState } from "../../src/components/StudentDataState";
import { useAuth } from "../../src/contexts/AuthContext";
import { useSync } from "../../src/contexts/SyncContext";
import { assessmentDocumentId, currentAcademicYear, fetchAdminAssessments, type AdminAssessmentData, type TermStatus } from "../../src/services/adminAssessmentService";
import { classNameFor, fetchAdminDirectory, type AdminDirectoryData } from "../../src/services/adminService";

const statuses: TermStatus[] = ["planned", "active", "closed"];
export default function AdminAssessmentsPage() {
  const { user } = useAuth(); const { queueWrite } = useSync(); const [directory, setDirectory] = useState<AdminDirectoryData | null>(null); const [data, setData] = useState<AdminAssessmentData | null>(null); const [termName, setTermName] = useState("Term 1"); const [year, setYear] = useState(currentAcademicYear()); const [termStart, setTermStart] = useState(""); const [termEnd, setTermEnd] = useState(""); const [status, setStatus] = useState<TermStatus>("planned"); const [examName, setExamName] = useState(""); const [classId, setClassId] = useState(""); const [termId, setTermId] = useState(""); const [examStart, setExamStart] = useState(""); const [examEnd, setExamEnd] = useState(""); const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false); const [offline, setOffline] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { if (!user) return; setLoading(true); setError(""); try { const [directoryResult, assessmentResult] = await Promise.all([fetchAdminDirectory(user.uid), fetchAdminAssessments(user.uid)]); setDirectory(directoryResult.data); setData(assessmentResult); setOffline(directoryResult.source === "cache" || assessmentResult.source === "cache"); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Unable to load assessment settings."); } finally { setLoading(false); } }, [user]); useEffect(() => { void load(); }, [load]);
  const createTerm = async () => { if (!termName.trim() || !year.trim() || !termStart || !termEnd) return setError("Enter the term name, academic year, and dates."); setSaving(true); setError(""); try { const id = assessmentDocumentId("TERM"); const result = await queueWrite({ path: `terms/${id}`, type: "set", merge: false, serverTimestampFields: ["createdAt"], data: { name: termName.trim(), academicYear: year.trim(), startDate: termStart, endDate: termEnd, status } }); setTermStart(""); setTermEnd(""); setNotice(result === "synced" ? "Academic term created." : "Academic term saved offline and queued."); await load(); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "Unable to create academic term."); } finally { setSaving(false); } };
  const createExam = async () => { const term = data?.terms.find((item) => item.id === termId); if (!term || !examName.trim() || !classId || !examStart) return setError("Enter an exam name, class, term, and start date."); setSaving(true); setError(""); try { const id = assessmentDocumentId("EXAM"); const result = await queueWrite({ path: `exams/${id}`, type: "set", merge: false, serverTimestampFields: ["createdAt"], data: { name: examName.trim(), classId, termId, term: term.name, academicYear: term.academicYear, startDate: examStart, endDate: examEnd } }); setExamName(""); setClassId(""); setTermId(""); setExamStart(""); setExamEnd(""); setNotice(result === "synced" ? "Exam window created." : "Exam window saved offline and queued."); await load(); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "Unable to create exam window."); } finally { setSaving(false); } };
  const removeTerm = async (id: string) => { if (data?.exams.some((exam) => exam.termId === id)) return setError("Remove exam windows assigned to this term first."); await remove(`terms/${id}`, "Academic term removed."); };
  const remove = async (path: string, success: string) => { setSaving(true); setError(""); try { const result = await queueWrite({ path, type: "delete" }); setNotice(result === "synced" ? success : "Removal saved offline and queued."); await load(); } catch (removeError) { setError(removeError instanceof Error ? removeError.message : "Unable to remove this item."); } finally { setSaving(false); } };
  return <AdminPageShell subtitle="Configure academic terms and class exam windows for grading and reporting." title="Assessment setup"><StudentDataState error={error} loading={loading} offline={offline} onRefresh={load} />{!!notice && <Text className="mt-4 rounded-2xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">{notice}</Text>}<Form title="New academic term"><Input placeholder="Term name" value={termName} setValue={setTermName} /><Input placeholder="Academic year" value={year} setValue={setYear} /><Input placeholder="Start date: YYYY-MM-DD" value={termStart} setValue={setTermStart} /><Input placeholder="End date: YYYY-MM-DD" value={termEnd} setValue={setTermEnd} /><Choices options={statuses} selected={status} setSelected={(value) => setStatus(value as TermStatus)} /><Button label="Add academic term" saving={saving} onPress={createTerm} /></Form><Text className="mt-6 text-lg font-extrabold text-slate-900">Academic terms</Text>{data?.terms.map((term) => <Card key={term.id} title={term.name} meta={`${term.academicYear} | ${term.status}`} detail={`${term.startDate} to ${term.endDate}`} pending={term.pending} saving={saving} remove={() => removeTerm(term.id)} />)}<Form title="New exam window"><Input placeholder="Exam name" value={examName} setValue={setExamName} /><Text className="mt-3 text-xs font-bold uppercase text-slate-500">Class</Text><Choices options={(directory?.classes || []).map((item) => item.classId || item.id)} labels={(directory?.classes || []).map((item) => item.name)} selected={classId} setSelected={setClassId} /><Text className="mt-1 text-xs font-bold uppercase text-slate-500">Term</Text><Choices options={(data?.terms || []).map((item) => item.id)} labels={(data?.terms || []).map((item) => `${item.name} | ${item.academicYear}`)} selected={termId} setSelected={setTermId} /><Input placeholder="Start date: YYYY-MM-DD" value={examStart} setValue={setExamStart} /><Input placeholder="End date: YYYY-MM-DD (optional)" value={examEnd} setValue={setExamEnd} /><Button label="Add exam window" saving={saving} onPress={createExam} /></Form><Text className="mt-6 text-lg font-extrabold text-slate-900">Exam windows</Text>{data?.exams.map((exam) => <Card key={exam.id} title={exam.name} meta={`${classNameFor(directory?.classes || [], exam.classId)} | ${exam.term}`} detail={`${exam.startDate}${exam.endDate ? ` to ${exam.endDate}` : ""} | ${exam.academicYear}`} pending={exam.pending} saving={saving} remove={() => remove(`exams/${exam.id}`, "Exam window removed.")} />)}</AdminPageShell>;
}
function Form({ title, children }: { title: string; children: React.ReactNode }) { return <View className="mt-5 rounded-3xl bg-white p-5"><Text className="text-lg font-extrabold text-slate-900">{title}</Text>{children}</View>; }
function Input({ placeholder, value, setValue }: { placeholder: string; value: string; setValue: (value: string) => void }) { return <TextInput className="mt-3 rounded-2xl bg-slate-50 px-4 py-4 text-base" onChangeText={setValue} placeholder={placeholder} placeholderTextColor="#94a3b8" value={value} />; }
function Choices({ options, labels, selected, setSelected }: { options: readonly string[]; labels?: readonly string[]; selected: string; setSelected: (value: string) => void }) { return <View className="mt-3 flex-row flex-wrap">{options.map((item, index) => <Pressable className={`mb-2 mr-2 rounded-full px-3 py-3 ${selected === item ? "bg-indigo-700" : "bg-slate-100"}`} key={item} onPress={() => setSelected(item)}><Text className={`text-xs font-bold capitalize ${selected === item ? "text-white" : "text-slate-700"}`}>{labels?.[index] || item}</Text></Pressable>)}</View>; }
function Button({ label, saving, onPress }: { label: string; saving: boolean; onPress: () => void }) { return <Pressable className="mt-3 items-center rounded-2xl bg-indigo-700 px-4 py-4" disabled={saving} onPress={onPress}><Text className="text-sm font-bold text-white">{saving ? "Saving..." : label}</Text></Pressable>; }
function Card({ title, meta, detail, pending, saving, remove }: { title: string; meta: string; detail: string; pending: boolean; saving: boolean; remove: () => void }) { return <View className="mt-3 rounded-3xl bg-white p-5"><Text className="text-base font-extrabold text-slate-900">{title}</Text><Text className="mt-1 text-xs uppercase text-slate-500">{meta}</Text><Text className="mt-3 text-sm text-slate-600">{detail}</Text>{pending ? <Text className="mt-2 text-xs font-bold uppercase text-amber-700">Queued</Text> : <Pressable className="mt-3 items-center rounded-2xl bg-red-50 px-4 py-3" disabled={saving} onPress={remove}><Text className="text-sm font-bold text-red-700">Remove</Text></Pressable>}</View>; }
