import { useCallback, useEffect, useState } from "react";
import { Pressable, Text, TextInput, View } from "react-native";
import { AdminPageShell } from "../../src/components/AdminPageShell";
import { StudentDataState } from "../../src/components/StudentDataState";
import { useAuth } from "../../src/contexts/AuthContext";
import { useSync } from "../../src/contexts/SyncContext";
import { communicationDocumentId, fetchAdminCommunications, type AdminCommunicationData, type Audience, type EventType } from "../../src/services/adminCommunicationService";

const audiences: Audience[] = ["all", "admin", "teacher", "student", "parent"]; const eventTypes: EventType[] = ["academic", "exam", "holiday", "meeting", "activity"];
export default function AdminCalendarPage() {
  const { user } = useAuth(); const { queueWrite } = useSync(); const [data, setData] = useState<AdminCommunicationData | null>(null); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [startDate, setStartDate] = useState(""); const [endDate, setEndDate] = useState(""); const [location, setLocation] = useState(""); const [audience, setAudience] = useState<Audience>("all"); const [eventType, setEventType] = useState<EventType>("academic"); const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false); const [offline, setOffline] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { if (!user) return; setLoading(true); setError(""); try { const result = await fetchAdminCommunications(user.uid); setData(result); setOffline(result.source === "cache"); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Unable to load calendar events."); } finally { setLoading(false); } }, [user]); useEffect(() => { void load(); }, [load]);
  const create = async () => { if (!title.trim() || !startDate) return setError("Enter a title and start date."); setSaving(true); setError(""); try { const id = communicationDocumentId("EVT"); const result = await queueWrite({ path: `calendarEvents/${id}`, type: "set", merge: false, serverTimestampFields: ["createdAt"], data: { title: title.trim(), description: description.trim(), eventType, audience, startDate, endDate, location: location.trim(), createdBy: user?.uid || "" } }); setTitle(""); setDescription(""); setStartDate(""); setEndDate(""); setLocation(""); setNotice(result === "synced" ? "Calendar event saved." : "Calendar event saved offline and queued."); await load(); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "Unable to save calendar event."); } finally { setSaving(false); } };
  const remove = async (id: string) => { setSaving(true); try { const result = await queueWrite({ path: `calendarEvents/${id}`, type: "delete" }); setNotice(result === "synced" ? "Calendar event removed." : "Removal queued."); await load(); } finally { setSaving(false); } };
  return <AdminPageShell subtitle="Maintain term dates, exams, holidays, meetings, and activities." title="Academic calendar"><StudentDataState error={error} loading={loading} offline={offline} onRefresh={load} />{!!notice && <Text className="mt-4 rounded-2xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">{notice}</Text>}<View className="mt-5 rounded-3xl bg-white p-5"><Text className="text-lg font-extrabold text-slate-900">New calendar event</Text><Input placeholder="Title" value={title} setValue={setTitle} /><Input placeholder="Description" value={description} setValue={setDescription} /><Input placeholder="Start date: YYYY-MM-DD" value={startDate} setValue={setStartDate} /><Input placeholder="End date: YYYY-MM-DD (optional)" value={endDate} setValue={setEndDate} /><Input placeholder="Location (optional)" value={location} setValue={setLocation} /><Choices options={audiences} selected={audience} setSelected={(value) => setAudience(value as Audience)} /><Choices options={eventTypes} selected={eventType} setSelected={(value) => setEventType(value as EventType)} /><Button label="Save calendar event" saving={saving} onPress={create} /></View><View className="mt-5">{data?.events.map((item) => <View className="mb-3 rounded-3xl bg-white p-5" key={item.id}><Text className="text-lg font-extrabold text-slate-900">{item.title}</Text><Text className="mt-1 text-xs uppercase text-slate-500">{item.eventType} | {item.audience}</Text><Text className="mt-3 text-sm font-bold text-indigo-700">{item.startDate}{item.endDate ? ` - ${item.endDate}` : ""}</Text>{!!item.location && <Text className="mt-2 text-sm text-slate-500">{item.location}</Text>}{item.pending ? <Text className="mt-3 text-xs font-bold uppercase text-amber-700">Queued</Text> : <Button label="Remove event" saving={saving} onPress={() => remove(item.id)} danger />}</View>)}</View></AdminPageShell>;
}
function Input({ placeholder, value, setValue }: { placeholder: string; value: string; setValue: (value: string) => void }) { return <TextInput className="mt-3 rounded-2xl bg-slate-50 px-4 py-4 text-base" onChangeText={setValue} placeholder={placeholder} placeholderTextColor="#94a3b8" value={value} />; }
function Choices({ options, selected, setSelected }: { options: readonly string[]; selected: string; setSelected: (value: string) => void }) { return <View className="mt-3 flex-row flex-wrap">{options.map((item) => <Pressable className={`mb-2 mr-2 rounded-full px-3 py-3 ${selected === item ? "bg-indigo-700" : "bg-slate-100"}`} key={item} onPress={() => setSelected(item)}><Text className={`text-xs font-bold capitalize ${selected === item ? "text-white" : "text-slate-700"}`}>{item}</Text></Pressable>)}</View>; }
function Button({ label, saving, onPress, danger = false }: { label: string; saving: boolean; onPress: () => void; danger?: boolean }) { return <Pressable className={`mt-3 items-center rounded-2xl px-4 py-4 ${danger ? "bg-red-50" : "bg-indigo-700"}`} disabled={saving} onPress={onPress}><Text className={`text-sm font-bold ${danger ? "text-red-700" : "text-white"}`}>{saving ? "Saving..." : label}</Text></Pressable>; }
