import { useCallback, useEffect, useMemo, useState } from "react";
import { Pressable, Text, TextInput, View } from "react-native";
import { AdminPageShell } from "../../src/components/AdminPageShell";
import { StudentDataState } from "../../src/components/StudentDataState";
import { useAuth } from "../../src/contexts/AuthContext";
import { useSync } from "../../src/contexts/SyncContext";
import { fetchAdminDirectory, type AdminDirectoryData, type StudentDirectoryRecord } from "../../src/services/adminService";
import { fetchAdminFamilyReports, type AdminFamilyReportData, type ParentDirectoryRecord } from "../../src/services/adminFamilyReportService";

export default function AdminFamilyLinksPage() {
  const { user } = useAuth(); const { queueWrite } = useSync(); const [directory, setDirectory] = useState<AdminDirectoryData | null>(null); const [data, setData] = useState<AdminFamilyReportData | null>(null); const [studentId, setStudentId] = useState(""); const [parentId, setParentId] = useState(""); const [search, setSearch] = useState(""); const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false); const [offline, setOffline] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { if (!user) return; setLoading(true); setError(""); try { const [directoryResult, familyResult] = await Promise.all([fetchAdminDirectory(user.uid), fetchAdminFamilyReports(user.uid)]); setDirectory(directoryResult.data); setData(familyResult); setOffline(directoryResult.source === "cache" || familyResult.source === "cache"); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Unable to load family links."); } finally { setLoading(false); } }, [user]); useEffect(() => { void load(); }, [load]);
  const parentsById = useMemo(() => new Map((data?.parents || []).map((item) => [item.parentId, item])), [data]); const students = directory?.students || []; const filtered = students.filter((student) => !search.trim() || `${student.displayName} ${student.studentId}`.toLowerCase().includes(search.trim().toLowerCase())); const unresolvedStudents = students.filter((student) => !student.parentId || !parentsById.get(student.parentId)?.studentIds.includes(student.studentId)).length; const unresolvedParents = (data?.parents || []).filter((parent) => !students.some((student) => student.parentId === parent.parentId)).length;
  const saveParent = async (parent: ParentDirectoryRecord, studentIds: string[]) => queueWrite({ path: `parents/${parent.id}`, type: "set", merge: true, serverTimestampFields: ["updatedAt"], data: { studentIds: [...new Set(studentIds)] } });
  const link = async () => { const student = students.find((item) => item.studentId === studentId); const parent = data?.parents.find((item) => item.parentId === parentId); if (!student || !parent) return setError("Select both a student and parent."); setSaving(true); setError(""); try { let pending = (await queueWrite({ path: `students/${student.id}`, type: "set", merge: true, serverTimestampFields: ["updatedAt"], data: { parentId: parent.parentId } })) === "pending"; if ((await saveParent(parent, [...parent.studentIds, student.studentId])) === "pending") pending = true; const previous = student.parentId ? parentsById.get(student.parentId) : undefined; if (previous && previous.parentId !== parent.parentId && (await saveParent(previous, previous.studentIds.filter((id) => id !== student.studentId))) === "pending") pending = true; setStudentId(""); setParentId(""); setNotice(pending ? "Family link saved offline and queued." : "Student and parent profiles linked."); await load(); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "Unable to link these profiles."); } finally { setSaving(false); } };
  const unlink = async (student: StudentDirectoryRecord) => { const parent = student.parentId ? parentsById.get(student.parentId) : undefined; if (!parent) return; setSaving(true); try { let pending = (await queueWrite({ path: `students/${student.id}`, type: "set", merge: true, serverTimestampFields: ["updatedAt"], data: { parentId: "" } })) === "pending"; if ((await saveParent(parent, parent.studentIds.filter((id) => id !== student.studentId))) === "pending") pending = true; setNotice(pending ? "Family unlink saved offline and queued." : "Parent link removed."); await load(); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "Unable to remove parent link."); } finally { setSaving(false); } };
  return <AdminPageShell subtitle="Resolve family access by maintaining student and parent profiles together." title="Parent-student links"><StudentDataState error={error} loading={loading} offline={offline} onRefresh={load} />{!!notice && <Text className="mt-4 rounded-2xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">{notice}</Text>}<View className="mt-5 flex-row"><Summary label="Students to review" value={unresolvedStudents} /><Summary label="Parents to review" value={unresolvedParents} /></View><View className="mt-4 rounded-3xl bg-white p-5"><Text className="text-lg font-extrabold text-slate-900">Link profiles</Text><Text className="mt-4 text-xs font-bold uppercase text-slate-500">Student</Text><View className="mt-2 flex-row flex-wrap">{students.map((student) => <Choice key={student.id} label={student.displayName} active={studentId === student.studentId} onPress={() => setStudentId(student.studentId)} />)}</View><Text className="mt-3 text-xs font-bold uppercase text-slate-500">Parent</Text><View className="mt-2 flex-row flex-wrap">{data?.parents.map((parent) => <Choice key={parent.id} label={parent.displayName} active={parentId === parent.parentId} onPress={() => setParentId(parent.parentId)} />)}</View><Pressable className="mt-3 items-center rounded-2xl bg-indigo-700 px-4 py-4" disabled={saving} onPress={link}><Text className="text-sm font-bold text-white">{saving ? "Saving..." : "Link profiles"}</Text></Pressable></View><TextInput className="mt-5 rounded-2xl bg-white px-4 py-4 text-base" onChangeText={setSearch} placeholder="Search student name or ID" placeholderTextColor="#94a3b8" value={search} /><View className="mt-4">{filtered.map((student) => { const parent = student.parentId ? parentsById.get(student.parentId) : undefined; const synced = !!parent && parent.studentIds.includes(student.studentId); return <View className="mb-3 rounded-3xl bg-white p-5" key={student.id}><Text className="text-base font-extrabold text-slate-900">{student.displayName}</Text><Text className="mt-1 text-xs text-slate-500">{student.studentId}</Text><Text className="mt-3 text-sm text-slate-600">{parent ? `${parent.displayName} | ${parent.parentId}` : "No parent linked"}</Text><Text className={`mt-2 text-xs font-bold uppercase ${synced ? "text-emerald-700" : "text-amber-700"}`}>{synced ? "Linked" : "Needs review"}</Text>{parent && <Pressable className="mt-3 items-center rounded-2xl bg-red-50 px-4 py-3" disabled={saving} onPress={() => unlink(student)}><Text className="text-sm font-bold text-red-700">Remove parent link</Text></Pressable>}</View>; })}</View></AdminPageShell>;
}
function Choice({ label, active, onPress }: { label: string; active: boolean; onPress: () => void }) { return <Pressable className={`mb-2 mr-2 rounded-full px-4 py-3 ${active ? "bg-indigo-700" : "bg-slate-100"}`} onPress={onPress}><Text className={`text-sm font-bold ${active ? "text-white" : "text-slate-700"}`}>{label}</Text></Pressable>; }
function Summary({ label, value }: { label: string; value: number }) { return <View className="mr-3 flex-1 rounded-3xl bg-white p-4"><Text className="text-xs font-bold uppercase text-slate-500">{label}</Text><Text className="mt-2 text-3xl font-black text-indigo-900">{value}</Text></View>; }
