import { useCallback, useEffect, useState } from "react";
import { Pressable, Text, TextInput, View } from "react-native";
import { AdminPageShell } from "../../src/components/AdminPageShell";
import { StudentDataState } from "../../src/components/StudentDataState";
import { useAuth } from "../../src/contexts/AuthContext";
import { useSync } from "../../src/contexts/SyncContext";
import { communicationDocumentId, fetchAdminCommunications, type AdminCommunicationData, type CommunicationCategory } from "../../src/services/adminCommunicationService";

const roles = ["admin", "teacher", "student", "parent"]; const categories: CommunicationCategory[] = ["announcement", "info", "alert"];
export default function AdminNotificationsPage() {
  const { user } = useAuth(); const { queueWrite } = useSync(); const [data, setData] = useState<AdminCommunicationData | null>(null); const [title, setTitle] = useState(""); const [messageText, setMessageText] = useState(""); const [target, setTarget] = useState("all"); const [role, setRole] = useState(""); const [category, setCategory] = useState<CommunicationCategory>("info"); const [route, setRoute] = useState(""); const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false); const [offline, setOffline] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { if (!user) return; setLoading(true); setError(""); try { const result = await fetchAdminCommunications(user.uid); setData(result); setOffline(result.source === "cache"); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Unable to load notifications."); } finally { setLoading(false); } }, [user]); useEffect(() => { void load(); }, [load]);
  const create = async () => { if (!title.trim() || !messageText.trim()) return setError("Enter a title and message."); setSaving(true); setError(""); try { const id = communicationDocumentId("NTF"); const result = await queueWrite({ path: `notifications/${id}`, type: "set", merge: false, serverTimestampFields: ["createdAt"], data: { title: title.trim(), message: messageText.trim(), target: target.trim() || "all", recipientRoles: role ? [role] : [], category, route: route.trim(), active: true, createdBy: user?.uid || "" } }); setTitle(""); setMessageText(""); setTarget("all"); setRole(""); setRoute(""); setNotice(result === "synced" ? "Notification published." : "Notification saved offline and queued."); await load(); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "Unable to publish notification."); } finally { setSaving(false); } };
  const remove = async (id: string) => { setSaving(true); try { const result = await queueWrite({ path: `notifications/${id}`, type: "delete" }); setNotice(result === "synced" ? "Notification removed." : "Removal queued."); await load(); } finally { setSaving(false); } };
  return <AdminPageShell subtitle="Publish workflow alerts for everyone, a role, or a student ID." title="Notifications"><StudentDataState error={error} loading={loading} offline={offline} onRefresh={load} />{!!notice && <Text className="mt-4 rounded-2xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">{notice}</Text>}<View className="mt-5 rounded-3xl bg-white p-5"><Text className="text-lg font-extrabold text-slate-900">New notification</Text><Input placeholder="Title" value={title} setValue={setTitle} /><Input placeholder="Message" value={messageText} setValue={setMessageText} /><Input placeholder="Target: all or student ID" value={target} setValue={setTarget} /><Input placeholder="Workflow route (optional)" value={route} setValue={setRoute} /><Choices options={["", ...roles]} selected={role} setSelected={setRole} emptyLabel="No role filter" /><Choices options={categories} selected={category} setSelected={(value) => setCategory(value as CommunicationCategory)} /><Button label="Publish notification" saving={saving} onPress={create} /></View><View className="mt-5">{data?.notifications.map((item) => <View className="mb-3 rounded-3xl bg-white p-5" key={item.id}><Text className="text-lg font-extrabold text-slate-900">{item.title}</Text><Text className="mt-1 text-xs uppercase text-slate-500">{item.category} | target: {item.target}{item.recipientRoles.length ? ` | ${item.recipientRoles.join(", ")}` : ""}</Text><Text className="mt-3 text-sm leading-6 text-slate-600">{item.message}</Text>{item.pending ? <Text className="mt-3 text-xs font-bold uppercase text-amber-700">Queued</Text> : <Button label="Remove notification" saving={saving} onPress={() => remove(item.id)} danger />}</View>)}</View></AdminPageShell>;
}
function Input({ placeholder, value, setValue }: { placeholder: string; value: string; setValue: (value: string) => void }) { return <TextInput className="mt-3 rounded-2xl bg-slate-50 px-4 py-4 text-base" onChangeText={setValue} placeholder={placeholder} placeholderTextColor="#94a3b8" value={value} />; }
function Choices({ options, selected, setSelected, emptyLabel = "" }: { options: readonly string[]; selected: string; setSelected: (value: string) => void; emptyLabel?: string }) { return <View className="mt-3 flex-row flex-wrap">{options.map((item) => <Pressable className={`mb-2 mr-2 rounded-full px-3 py-3 ${selected === item ? "bg-indigo-700" : "bg-slate-100"}`} key={item || "empty"} onPress={() => setSelected(item)}><Text className={`text-xs font-bold capitalize ${selected === item ? "text-white" : "text-slate-700"}`}>{item || emptyLabel}</Text></Pressable>)}</View>; }
function Button({ label, saving, onPress, danger = false }: { label: string; saving: boolean; onPress: () => void; danger?: boolean }) { return <Pressable className={`mt-3 items-center rounded-2xl px-4 py-4 ${danger ? "bg-red-50" : "bg-indigo-700"}`} disabled={saving} onPress={onPress}><Text className={`text-sm font-bold ${danger ? "text-red-700" : "text-white"}`}>{saving ? "Saving..." : label}</Text></Pressable>; }
