import { useCallback, useEffect, useState } from "react";
import { Pressable, Text, TextInput, View } from "react-native";
import { AdminPageShell } from "../../src/components/AdminPageShell";
import { StudentDataState } from "../../src/components/StudentDataState";
import { useAuth } from "../../src/contexts/AuthContext";
import { useSync } from "../../src/contexts/SyncContext";
import { fetchAdminDirectory, type AdminDirectoryData } from "../../src/services/adminService";
import { buildPublishedReport, currentAcademicYear, fetchAdminFamilyReports, reportDocumentId, type AdminFamilyReportData } from "../../src/services/adminFamilyReportService";

const terms = ["Term 1", "Term 2", "Term 3"];
export default function AdminReportPublishingPage() {
  const { user } = useAuth(); const { queueWrite } = useSync(); const [directory, setDirectory] = useState<AdminDirectoryData | null>(null); const [data, setData] = useState<AdminFamilyReportData | null>(null); const [studentId, setStudentId] = useState(""); const [academicYear, setAcademicYear] = useState(currentAcademicYear()); const [term, setTerm] = useState("Term 1"); const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false); const [offline, setOffline] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { if (!user) return; setLoading(true); setError(""); try { const [directoryResult, reportResult] = await Promise.all([fetchAdminDirectory(user.uid), fetchAdminFamilyReports(user.uid)]); setDirectory(directoryResult.data); setData(reportResult); setOffline(directoryResult.source === "cache" || reportResult.source === "cache"); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Unable to load report publishing data."); } finally { setLoading(false); } }, [user]); useEffect(() => { void load(); }, [load]);
  const publish = async () => { if (!user || !data) return; const student = directory?.students.find((item) => item.studentId === studentId); if (!student || !academicYear.trim()) return setError("Select a student and enter the academic year."); setSaving(true); setError(""); try { const report = buildPublishedReport(student, directory?.classes || [], data, academicYear.trim(), term); const result = await queueWrite({ path: `studentReports/${reportDocumentId(student.studentId, academicYear.trim(), term)}`, type: "set", merge: true, serverTimestampFields: ["publishedAt", "updatedAt"], data: { ...report, publishedBy: user.uid } }); setNotice(result === "synced" ? "Report snapshot published to the parent portal." : "Report snapshot saved offline and queued."); await load(); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "Unable to publish report."); } finally { setSaving(false); } };
  return <AdminPageShell subtitle="Release reviewed term snapshots to linked parent accounts." title="Report publishing"><StudentDataState error={error} loading={loading} offline={offline} onRefresh={load} />{!!notice && <Text className="mt-4 rounded-2xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">{notice}</Text>}<View className="mt-5 rounded-3xl bg-white p-5"><Text className="text-lg font-extrabold text-slate-900">Publish term report</Text><Text className="mt-4 text-xs font-bold uppercase tracking-widest text-slate-500">Student</Text><View className="mt-2 flex-row flex-wrap">{directory?.students.filter((item) => item.status !== "archived").map((student) => <Choice key={student.id} label={student.displayName} active={studentId === student.studentId} onPress={() => setStudentId(student.studentId)} />)}</View><TextInput className="mt-3 rounded-2xl bg-slate-50 px-4 py-4 text-base" onChangeText={setAcademicYear} placeholder="Academic year" placeholderTextColor="#94a3b8" value={academicYear} /><View className="mt-3 flex-row flex-wrap">{terms.map((item) => <Choice key={item} label={item} active={term === item} onPress={() => setTerm(item)} />)}</View><Pressable className="mt-3 items-center rounded-2xl bg-indigo-700 px-4 py-4" disabled={saving} onPress={publish}><Text className="text-sm font-bold text-white">{saving ? "Publishing..." : "Publish report snapshot"}</Text></Pressable></View><Text className="mt-6 text-lg font-extrabold text-slate-900">Released reports</Text>{data?.reports.map((report) => <View className="mt-3 rounded-3xl bg-white p-5" key={report.id}><View className="flex-row justify-between"><View className="mr-3 flex-1"><Text className="text-base font-extrabold text-slate-900">{report.studentName}</Text><Text className="mt-1 text-xs text-slate-500">{report.studentId} | {report.className}</Text></View><Text className="font-black text-indigo-800">{report.averageGrade.toFixed(1)}%</Text></View><Text className="mt-3 text-sm text-slate-600">{report.term} | {report.academicYear} | {report.subjects.length} subjects</Text>{report.pending && <Text className="mt-2 text-xs font-bold uppercase text-amber-700">Queued</Text>}</View>)}</AdminPageShell>;
}
function Choice({ label, active, onPress }: { label: string; active: boolean; onPress: () => void }) { return <Pressable className={`mb-2 mr-2 rounded-full px-4 py-3 ${active ? "bg-indigo-700" : "bg-slate-100"}`} onPress={onPress}><Text className={`text-sm font-bold ${active ? "text-white" : "text-slate-700"}`}>{label}</Text></Pressable>; }
