import { RefreshCw, ShieldCheck } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { collection, getDocs } from "firebase/firestore";
import { db } from "../../firebaseConfig";

type AuditItem = { id: string; assignmentName?: string; studentName?: string; aiSuggestion?: { score: number; feedback: string; model?: string; status?: string }; aiApprovedBy?: string; aiRejectedBy?: string };
type Filter = "all" | "pending" | "approved" | "rejected";
const decisionOf = (item: AuditItem) => item.aiSuggestion?.status === "approved" ? "approved" : item.aiSuggestion?.status === "rejected" ? "rejected" : "pending";

export default function AiAssessmentAuditPage() {
  const [items, setItems] = useState<AuditItem[]>([]); const [filter, setFilter] = useState<Filter>("all"); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = async () => { setLoading(true); setError(""); try { const snapshot = await getDocs(collection(db, "submissions")); setItems(snapshot.docs.map((item) => ({ id: item.id, ...item.data() } as AuditItem)).filter((item) => !!item.aiSuggestion)); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Unable to load AI audit records."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const counts = useMemo(() => ({ all: items.length, pending: items.filter((item) => decisionOf(item) === "pending").length, approved: items.filter((item) => decisionOf(item) === "approved").length, rejected: items.filter((item) => decisionOf(item) === "rejected").length }), [items]);
  const visibleItems = filter === "all" ? items : items.filter((item) => decisionOf(item) === filter);
  return <div className="mx-auto max-w-6xl space-y-6"><div className="flex items-end justify-between gap-3"><div><p className="flex items-center gap-2 text-sm font-semibold uppercase tracking-wider text-indigo-600"><ShieldCheck size={16} /> AI controls</p><h1 className="mt-1 text-3xl font-bold text-slate-900">AI grading audit</h1><p className="mt-2 text-sm text-slate-500">Review generated suggestions and the teacher decision recorded for each submission.</p></div><button onClick={() => void load()} className="flex items-center gap-2 rounded-lg border px-3 py-2 text-sm font-semibold"><RefreshCw size={16} /> Refresh</button></div>{error && <div className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</div>}<div className="grid grid-cols-2 gap-3 md:grid-cols-4">{(["all", "pending", "approved", "rejected"] as Filter[]).map((value) => <button key={value} onClick={() => setFilter(value)} className={`rounded-xl border p-4 text-left ${filter === value ? "border-indigo-500 bg-indigo-50" : "border-slate-200 bg-white"}`}><p className="text-xs font-semibold uppercase text-slate-500">{value}</p><p className="mt-1 text-2xl font-bold text-slate-900">{counts[value]}</p></button>)}</div>{loading ? <p className="text-sm text-slate-500">Loading audit records...</p> : <div className="overflow-x-auto rounded-xl border border-slate-200 bg-white shadow-sm"><table className="min-w-full text-left text-sm"><thead className="border-b bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">Submission</th><th className="px-4 py-3">Suggestion</th><th className="px-4 py-3">Model</th><th className="px-4 py-3">Decision</th><th className="px-4 py-3">Reviewer</th></tr></thead><tbody className="divide-y divide-slate-100">{visibleItems.map((item) => { const suggestion = item.aiSuggestion!; const decision = decisionOf(item); return <tr key={item.id}><td className="px-4 py-4"><p className="font-semibold text-slate-900">{item.assignmentName || "Assessment"}</p><p className="text-xs text-slate-500">{item.studentName || item.id}</p></td><td className="px-4 py-4"><span className="font-semibold">{suggestion.score}%</span><p className="mt-1 max-w-md text-xs text-slate-500">{suggestion.feedback}</p></td><td className="px-4 py-4 text-xs text-slate-500">{suggestion.model || "Configured provider"}</td><td className="px-4 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${decision === "approved" ? "bg-emerald-100 text-emerald-700" : decision === "rejected" ? "bg-red-100 text-red-700" : "bg-amber-100 text-amber-700"}`}>{decision}</span></td><td className="px-4 py-4 text-xs text-slate-500">{item.aiApprovedBy || item.aiRejectedBy || "—"}</td></tr>; })}</tbody></table>{!visibleItems.length && <p className="p-8 text-center text-sm text-slate-500">No AI grading records match this filter.</p>}</div>}</div>;
}
