import { useEffect, useMemo, useState } from "react";
import { ArchiveRestore, RefreshCw } from "lucide-react";
import { collection, getDocs, updateDoc, doc, serverTimestamp } from "firebase/firestore";
import { db } from "../../firebaseConfig";

type ArchivedRecord = { id: string; name: string; schoolId: string; type: "Student" | "Staff"; status?: string };

export default function ArchivePage() {
  const [records, setRecords] = useState<ArchivedRecord[]>([]); const [filter, setFilter] = useState<"all" | "Student" | "Staff">("all"); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const load = async () => { setLoading(true); setError(""); try { const [students, teachers, staff] = await Promise.all([getDocs(collection(db, "students")), getDocs(collection(db, "teachers")), getDocs(collection(db, "staff"))]); const rows = [...students.docs.map(item => ({ id: item.id, type: "Student" as const, data: item.data() })), ...teachers.docs.map(item => ({ id: item.id, type: "Staff" as const, data: item.data() })), ...staff.docs.map(item => ({ id: item.id, type: "Staff" as const, data: item.data() }))]; setRecords(rows.filter(item => item.data.status === "archived").map(item => ({ id: item.id, type: item.type, name: String(item.data.displayName || item.data.name || item.data.staffName || item.id), schoolId: String(item.data.studentId || item.data.staffId || item.data.teacherId || item.id), status: String(item.data.status || "archived") }))); } catch (value) { setError(value instanceof Error ? value.message : "Unable to load archived records."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const visible = useMemo(() => records.filter(item => filter === "all" || item.type === filter), [records, filter]);
  const restore = async (item: ArchivedRecord) => { setBusy(item.id); setError(""); try { const collectionName = item.type === "Student" ? "students" : "staff"; await updateDoc(doc(db, collectionName, item.id), { status: "active", loginDisabled: false, restoredAt: serverTimestamp() }); setRecords(current => current.filter(row => row.id !== item.id || row.type !== item.type)); setMessage(`${item.name} restored successfully.`); } catch (value) { setError(value instanceof Error ? value.message : "Unable to restore this record."); } finally { setBusy(""); } };
  return <main className="mx-auto max-w-6xl space-y-6"><header className="flex flex-wrap items-end justify-between gap-3"><div><p className="eyebrow">Records management</p><h1 className="mt-1 text-3xl font-black tracking-tight text-dark">Archive</h1><p className="mt-2 text-sm text-slate-500">Review graduated or inactive student and staff records. Restore a record when it is needed again.</p></div><button onClick={() => void load()} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold text-slate-700"><RefreshCw size={16} /> Refresh</button></header>{message && <p className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">{message}</p>}{error && <p className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</p>}<section className="surface overflow-hidden"><div className="flex flex-wrap gap-2 border-b border-slate-100 p-4">{(["all", "Student", "Staff"] as const).map(value => <button key={value} onClick={() => setFilter(value)} className={`rounded-xl px-4 py-2 text-sm font-bold ${filter === value ? "bg-primary text-white" : "bg-slate-100 text-slate-600"}`}>{value === "all" ? "All archived" : `${value} records`}</button>)}</div>{loading ? <p className="p-10 text-center text-sm text-slate-500">Loading archive...</p> : visible.length ? <div className="divide-y divide-slate-100">{visible.map(item => <div key={`${item.type}-${item.id}`} className="flex flex-wrap items-center justify-between gap-4 p-5"><div><p className="font-bold text-dark">{item.name}</p><p className="mt-1 text-xs text-slate-500">{item.type} · {item.schoolId}</p></div><button disabled={busy === item.id} onClick={() => void restore(item)} className="inline-flex items-center gap-2 rounded-xl bg-accent2 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50"><ArchiveRestore size={16} />{busy === item.id ? "Restoring..." : "Restore record"}</button></div>)}</div> : <div className="empty-state m-5">No archived records found.</div>}</section></main>;
}
