import { useEffect, useMemo, useState } from "react";
import { fetchStaffDirectory, fetchStudentDirectory, type StaffDirectoryRecord, type StudentDirectoryRecord } from "../../services/DirectoryService";
import { enrollAttendanceFace, getFaceEnrollments, type EnrollmentCandidate } from "../../services/AttendanceFaceEnrollmentService";

function toBase64(file: File) { return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(",")[1] || ""); reader.onerror = () => reject(reader.error); reader.readAsDataURL(file); }); }

export default function AttendanceFaceEnrollmentPage() {
  const [people, setPeople] = useState<EnrollmentCandidate[]>([]); const [enrolled, setEnrolled] = useState<Map<string, unknown>>(new Map()); const [selected, setSelected] = useState(""); const [file, setFile] = useState<File | null>(null); const [preview, setPreview] = useState(""); const [search, setSearch] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  useEffect(() => { void Promise.all([fetchStudentDirectory(), fetchStaffDirectory()]).then(async ([students, staff]) => { const candidates = [...(students as StudentDirectoryRecord[]).map(item => ({ id: item.id, schoolId: item.studentId, name: item.displayName, kind: "student" as const })), ...(staff as StaffDirectoryRecord[]).map(item => ({ id: item.id, schoolId: item.teacherId, name: item.displayName, kind: "staff" as const }))].filter(item => item.schoolId); setPeople(candidates); try { setEnrolled(await getFaceEnrollments()); } catch { setMessage("Enrollment statuses are protected; you can still enroll or replace a selected face."); } }).catch(value => setError(value instanceof Error ? value.message : "Unable to load enrollment candidates.")); }, []);
  const filtered = useMemo(() => people.filter(item => `${item.name} ${item.schoolId}`.toLowerCase().includes(search.toLowerCase())), [people, search]);
  const submit = async () => { const person = people.find(item => item.schoolId === selected); if (!person || !file) return setError("Select a person and a clear face photo."); setBusy(true); setError(""); setMessage(""); try { const imageBytes = await toBase64(file); if (!imageBytes) throw new Error("The selected image could not be read. Please capture or choose it again."); const result = await enrollAttendanceFace(person.schoolId, imageBytes); setEnrolled(current => new Map(current).set(person.schoolId, result)); setMessage(`${person.name} (${person.schoolId}) enrolled successfully.`); setFile(null); setPreview(""); } catch (value) { setError(value instanceof Error ? value.message : "Enrollment failed."); } finally { setBusy(false); } };
  return <main className="mx-auto max-w-6xl space-y-6"><header><p className="text-sm font-semibold uppercase tracking-wider text-indigo-600">Attendance identity</p><h1 className="mt-1 text-3xl font-bold text-slate-900">Face enrollment</h1><p className="mt-2 text-sm text-slate-500">Enroll one clear face photo per student or staff school ID. Re-enrolling replaces the application record and adds the new face securely.</p></header>{message && <p className="rounded-lg bg-emerald-50 p-4 text-emerald-700">{message}</p>}{error && <p className="rounded-lg bg-red-50 p-4 text-red-700">{error}</p>}<section className="grid gap-6 lg:grid-cols-[1fr_360px]"><div className="rounded-xl border bg-white p-5 shadow-sm"><input className="w-full rounded-lg border px-3 py-2.5" placeholder="Search name or school ID" value={search} onChange={event => setSearch(event.target.value)} /><div className="mt-4 max-h-[520px] overflow-auto">{filtered.map(item => <button key={`${item.kind}-${item.schoolId}`} onClick={() => setSelected(item.schoolId)} className={`mb-2 block w-full rounded-lg border p-3 text-left ${selected === item.schoolId ? "border-indigo-500 bg-indigo-50" : "border-slate-100"}`}><div className="flex justify-between gap-3"><span className="font-semibold">{item.name}</span><span className={`text-xs font-bold ${enrolled.has(item.schoolId) ? "text-emerald-700" : "text-amber-700"}`}>{enrolled.has(item.schoolId) ? "Enrolled" : "Not enrolled"}</span></div><p className="text-xs text-slate-500">{item.kind} · {item.schoolId}</p></button>)}{!filtered.length && <p className="p-6 text-center text-sm text-slate-500">No matching people.</p>}</div></div><div className="rounded-xl border bg-white p-5 shadow-sm"><h2 className="font-bold">{enrolled.has(selected) ? "Re-enroll face" : "Enroll face"}</h2><p className="mt-2 text-sm text-slate-500">Selected school ID: <strong>{selected || "None"}</strong></p><input className="mt-5 block w-full text-sm" type="file" accept="image/jpeg,image/png" capture="user" onChange={event => { const nextFile = event.target.files?.[0] || null; setFile(nextFile); setPreview(nextFile ? URL.createObjectURL(nextFile) : ""); setError(""); setMessage(""); }} />{preview && <img src={preview} alt="Captured face preview" className="mt-4 h-64 w-full rounded-xl border border-slate-200 object-cover" />}<button disabled={busy || !selected || !file} onClick={() => void submit()} className="mt-5 w-full rounded-lg bg-indigo-600 px-4 py-3 font-semibold text-white disabled:opacity-50">{busy ? "Processing photo..." : enrolled.has(selected) ? "Replace enrollment" : "Enroll face"}</button><p className="mt-4 text-xs leading-5 text-slate-500">Use a clear, front-facing photo containing one person. Face verification is securely managed by the school system.</p></div></section></main>;
}
