import { useEffect, useState } from "react";
import { Save } from "lucide-react";
import { useAuth } from "../../contexts/AuthContext";
import { fetchClasses } from "../../services/ClassService";
import { fetchClassSubjectSetup, saveClassSubjectSetup } from "../../services/SubjectSetupService";

export default function ClassSubjectSetupPage() {
  const { user } = useAuth(); const [classes, setClasses] = useState<any[]>([]); const [classId, setClassId] = useState(""); const [subjects, setSubjects] = useState<string[]>([]); const [draft, setDraft] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { void fetchClasses().then(setClasses).catch(e => setError(e instanceof Error ? e.message : "Unable to load classes.")); }, []);
  useEffect(() => { if (!classId) return setSubjects([]); void fetchClassSubjectSetup(classId).then(result => setSubjects(result.subjects)).catch(e => setError(e instanceof Error ? e.message : "Unable to load subjects.")); }, [classId]);
  const add = () => { const value = draft.trim(); if (value && !subjects.some(subject => subject.toLowerCase() === value.toLowerCase())) setSubjects([...subjects, value].sort()); setDraft(""); };
  const save = async () => { if (!user || !classId) return; setSaving(true); setError(""); try { await saveClassSubjectSetup(classId, subjects, user.uid); setMessage("Class subject list saved."); } catch (e) { setError(e instanceof Error ? e.message : "Unable to save subject list."); } finally { setSaving(false); } };
  return <div className="mx-auto max-w-3xl space-y-6"><div><p className="text-sm font-semibold uppercase tracking-wider text-primary">Academic setup</p><h1 className="mt-1 text-3xl font-bold text-slate-900">Subjects per class</h1><p className="mt-2 text-sm text-slate-500">Define the required subjects for each class before end-of-term marks are entered or published.</p></div>{message && <div className="rounded-lg bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{message}</div>}{error && <div className="rounded-lg bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}<section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><label className="block text-sm font-semibold text-slate-700">Class<select value={classId} onChange={e => { setClassId(e.target.value); setMessage(""); }} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2.5"><option value="">Select class</option>{classes.map(item => <option key={item.id} value={item.classId || item.id}>{item.name || item.classId || item.id}</option>)}</select></label>{classId && <><div className="mt-5 flex gap-2"><input value={draft} onChange={e => setDraft(e.target.value)} onKeyDown={e => { if (e.key === "Enter") { e.preventDefault(); add(); } }} placeholder="Add subject e.g. Mathematics" className="flex-1 rounded-lg border border-slate-300 px-3 py-2.5" /><button onClick={add} className="rounded-lg border border-primary px-4 py-2 font-semibold text-primary">Add</button></div><div className="mt-5 grid gap-2 sm:grid-cols-2">{subjects.map(subject => <div key={subject} className="flex items-center justify-between rounded-lg border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm font-medium"><span>{subject}</span><button onClick={() => setSubjects(subjects.filter(item => item !== subject))} className="text-red-600">Remove</button></div>)}</div><button disabled={saving || !subjects.length} onClick={() => void save()} className="mt-5 flex items-center gap-2 rounded-lg bg-primary px-4 py-2.5 font-semibold text-white disabled:opacity-50"><Save size={16} />{saving ? "Saving..." : "Save class subjects"}</button></>}</section></div>;
}
