import { useEffect, useMemo, useState } from "react";
import { ArrowLeftRight, BookOpen, CheckCircle2, LibraryBig, Plus, RotateCcw, Search, UserRound } from "lucide-react";
import { addLibraryBook, fetchLibraryBooks, fetchLibraryLoans, issueLibraryBook, returnLibraryBook, type LibraryBook, type LibraryLoan } from "../../services/LibraryService";

const inputClass = "w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none transition focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100";

export default function LibraryPage() {
  const [books, setBooks] = useState<LibraryBook[]>([]);
  const [loans, setLoans] = useState<LibraryLoan[]>([]);
  const [search, setSearch] = useState("");
  const [message, setMessage] = useState("");
  const [form, setForm] = useState({ title: "", bookNumber: "", author: "", category: "", isbn: "", shelfLocation: "", totalCopies: "1" });
  const [issue, setIssue] = useState({ bookId: "", borrowerId: "", borrowerName: "", dueDate: "" });

  const refresh = async () => { const [nextBooks, nextLoans] = await Promise.all([fetchLibraryBooks(), fetchLibraryLoans()]); setBooks(nextBooks); setLoans(nextLoans); };
  useEffect(() => { refresh().catch(() => setMessage("Unable to load library records.")); }, []);
  const visibleBooks = useMemo(() => books.filter((book) => `${book.title} ${book.author} ${book.category || ""}`.toLowerCase().includes(search.toLowerCase())), [books, search]);
  const overdue = loans.filter((loan) => loan.status === "overdue");

  const addBook = async (event: React.FormEvent) => { event.preventDefault(); try { await addLibraryBook({ ...form, totalCopies: Number(form.totalCopies) } as never); setForm({ title: "", bookNumber: "", author: "", category: "", isbn: "", shelfLocation: "", totalCopies: "1" }); setMessage("Book added to the catalogue."); await refresh(); } catch { setMessage("Could not add this book."); } };
  const issueBook = async (event: React.FormEvent) => { event.preventDefault(); try { const book = books.find((item) => item.id === issue.bookId); if (!book) throw new Error(); await issueLibraryBook(book, issue.borrowerId, issue.borrowerName, issue.dueDate); setIssue({ bookId: "", borrowerId: "", borrowerName: "", dueDate: "" }); setMessage("Book issued and borrower record updated."); await refresh(); } catch { setMessage("Could not issue this book. Check availability and required fields."); } };
  const returnBook = async (loan: LibraryLoan) => { try { await returnLibraryBook(loan); setMessage("Book returned successfully."); await refresh(); } catch { setMessage("Could not complete the return."); } };

  return <main className="min-h-screen bg-slate-50 p-4 md:p-8"><div className="mx-auto max-w-7xl space-y-6">
    <header className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><p className="text-sm font-semibold uppercase tracking-wider text-indigo-600">Academic operations</p><h1 className="mt-1 text-3xl font-bold text-slate-900">School library</h1><p className="mt-1 text-sm text-slate-500">Manage books, borrowing records, returns, and due dates.</p></div><div className="flex items-center gap-2 rounded-xl border border-indigo-100 bg-white px-4 py-3 text-sm text-slate-600"><LibraryBig className="text-indigo-600" size={20} /> {books.length} titles · {loans.filter((l) => l.status !== "returned").length} active loans</div></header>
    {message && <div className="rounded-lg border border-indigo-100 bg-indigo-50 px-4 py-3 text-sm text-indigo-800">{message}</div>}
    <section className="grid gap-4 md:grid-cols-3"><div className="rounded-xl border border-slate-200 bg-white p-4"><BookOpen className="text-indigo-600" /><p className="mt-3 text-2xl font-bold">{books.reduce((sum, b) => sum + b.totalCopies, 0)}</p><p className="text-sm text-slate-500">Total copies</p></div><div className="rounded-xl border border-slate-200 bg-white p-4"><CheckCircle2 className="text-emerald-600" /><p className="mt-3 text-2xl font-bold">{books.reduce((sum, b) => sum + b.availableCopies, 0)}</p><p className="text-sm text-slate-500">Available copies</p></div><div className="rounded-xl border border-amber-200 bg-amber-50 p-4"><RotateCcw className="text-amber-600" /><p className="mt-3 text-2xl font-bold">{overdue.length}</p><p className="text-sm text-amber-800">Overdue loans</p></div></section>
    <section className="grid gap-6 xl:grid-cols-2"><form onSubmit={addBook} className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="flex items-center gap-2 font-semibold text-slate-900"><Plus size={18} /> Add library book</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{([["title","Book title"],["bookNumber","Book number"],["author","Author"],["category","Category"],["isbn","ISBN"],["shelfLocation","Shelf location"],["totalCopies","Total copies"]] as const).map(([key, label]) => <input key={key} required={key === "title" || key === "bookNumber" || key === "author" || key === "totalCopies"} className={inputClass} type={key === "totalCopies" ? "number" : "text"} min={key === "totalCopies" ? 1 : undefined} placeholder={label} value={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} />)}</div><button className="mt-4 inline-flex items-center gap-2 rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-indigo-700"><Plus size={16} /> Add book</button></form>
    <form onSubmit={issueBook} className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="flex items-center gap-2 font-semibold text-slate-900"><ArrowLeftRight size={18} /> Issue a book</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><select required className={inputClass} value={issue.bookId} onChange={(e) => setIssue({ ...issue, bookId: e.target.value })}><option value="">Select available book</option>{books.filter((b) => b.availableCopies > 0).map((b) => <option key={b.id} value={b.id}>{b.title} ({b.availableCopies} available)</option>)}</select><input required className={inputClass} placeholder="Borrower name" value={issue.borrowerName} onChange={(e) => setIssue({ ...issue, borrowerName: e.target.value })} /><input required className={inputClass} placeholder="Student/user ID" value={issue.borrowerId} onChange={(e) => setIssue({ ...issue, borrowerId: e.target.value })} /><input required className={inputClass} type="date" value={issue.dueDate} onChange={(e) => setIssue({ ...issue, dueDate: e.target.value })} /></div><button className="mt-4 inline-flex items-center gap-2 rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white hover:bg-slate-700"><UserRound size={16} /> Record borrowing</button></form></section>
    <section className="rounded-xl border border-slate-200 bg-white"><div className="flex flex-col gap-3 border-b border-slate-100 p-5 md:flex-row md:items-center md:justify-between"><h2 className="font-semibold text-slate-900">Book catalogue</h2><div className="relative"><Search className="absolute left-3 top-2.5 text-slate-400" size={17} /><input className={`${inputClass} pl-9`} placeholder="Search title, author, category" value={search} onChange={(e) => setSearch(e.target.value)} /></div></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-4">Book</th><th className="p-4">Category</th><th className="p-4">Shelf</th><th className="p-4">Availability</th></tr></thead><tbody>{visibleBooks.map((book) => <tr key={book.id} className="border-t border-slate-100"><td className="p-4"><p className="font-semibold text-slate-900">{book.title}</p><p className="text-slate-500">{book.author}{book.isbn ? ` · ${book.isbn}` : ""}</p></td><td className="p-4 text-slate-600">{book.category || "—"}</td><td className="p-4 text-slate-600">{book.shelfLocation || "—"}</td><td className="p-4"><span className={book.availableCopies ? "text-emerald-700" : "text-rose-700"}>{book.availableCopies} / {book.totalCopies} available</span></td></tr>)}</tbody></table>{!visibleBooks.length && <p className="p-8 text-center text-sm text-slate-500">No books match your search.</p>}</div></section>
    <section className="rounded-xl border border-slate-200 bg-white"><div className="border-b border-slate-100 p-5"><h2 className="font-semibold text-slate-900">Borrowing activity</h2></div><div className="divide-y divide-slate-100">{loans.map((loan) => <div key={loan.id} className="flex flex-col gap-3 p-4 md:flex-row md:items-center md:justify-between"><div><p className="font-semibold text-slate-900">{loan.bookTitle}</p><p className="text-sm text-slate-500">{loan.borrowerName} · due {loan.dueDate}</p></div><div className="flex items-center gap-3"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${loan.status === "overdue" ? "bg-rose-100 text-rose-700" : loan.status === "returned" ? "bg-slate-100 text-slate-600" : "bg-amber-100 text-amber-700"}`}>{loan.status}</span>{loan.status !== "returned" && <button onClick={() => returnBook(loan)} className="rounded-lg border border-slate-200 px-3 py-1.5 text-xs font-semibold text-slate-700 hover:bg-slate-50">Record return</button>}</div></div>)}{!loans.length && <p className="p-8 text-center text-sm text-slate-500">No borrowing records yet.</p>}</div></section>
  </div></main>;
}
