import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, RefreshCw, XCircle } from "lucide-react";
import { getPaymentIntents, reconcilePaymentIntent, type PaymentIntent } from "../../services/PaymentIntentService";

export default function PaymentIntentsPage() {
  const [items, setItems] = useState<PaymentIntent[]>([]); const [filter, setFilter] = useState("all"); const [references, setReferences] = useState<Record<string, string>>({}); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = async () => { setLoading(true); try { setItems(await getPaymentIntents()); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Unable to load payment intents."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const filtered = useMemo(() => items.filter(item => filter === "all" || item.status === filter), [filter, items]);
  const reconcile = async (item: PaymentIntent, status: "paid" | "failed") => { try { await reconcilePaymentIntent(item.id, status, references[item.id] || item.providerReference || ""); await load(); } catch (reconcileError) { setError(reconcileError instanceof Error ? reconcileError.message : "Unable to reconcile payment."); } };
  return <div className="mx-auto max-w-7xl space-y-6"><div className="flex items-end justify-between gap-3"><div><p className="text-sm font-semibold uppercase tracking-wider text-primary">Finance</p><h1 className="mt-1 text-3xl font-bold text-slate-900">Payment intents</h1><p className="mt-2 text-sm text-slate-500">Monitor Mobile Money requests and reconcile provider outcomes.</p></div><button onClick={() => void load()} className="flex items-center gap-2 rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-semibold"><RefreshCw size={16} /> Refresh</button></div>{error && <div className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</div>}<select value={filter} onChange={event => setFilter(event.target.value)} className="rounded-lg border px-3 py-2 text-sm"><option value="all">All intents</option><option value="pending">Pending</option><option value="paid">Paid</option><option value="failed">Failed</option><option value="cancelled">Cancelled</option></select><section className="overflow-x-auto rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><table className="min-w-full text-left text-sm"><thead><tr className="border-b text-xs uppercase text-slate-500"><th className="px-3 py-3">Student</th><th className="px-3 py-3">Amount</th><th className="px-3 py-3">Provider</th><th className="px-3 py-3">Status</th><th className="px-3 py-3">Reference</th><th className="px-3 py-3">Actions</th></tr></thead><tbody>{filtered.map(item => <tr key={item.id} className="border-b"><td className="px-3 py-3 font-semibold">{item.studentId}<p className="text-xs font-normal text-slate-500">{item.phone}</p></td><td className="px-3 py-3">{item.currency} {item.amount.toFixed(2)}</td><td className="px-3 py-3 capitalize">{item.provider.replaceAll("-", " ")}</td><td className="px-3 py-3 capitalize">{item.status}</td><td className="px-3 py-3"><input value={references[item.id] || item.providerReference || ""} onChange={event => setReferences({ ...references, [item.id]: event.target.value })} className="w-36 rounded border px-2 py-1 text-xs" /></td><td className="px-3 py-3">{item.status === "pending" && <div className="flex gap-2"><button title="Mark paid" onClick={() => void reconcile(item, "paid")} className="text-emerald-700"><CheckCircle2 size={18} /></button><button title="Mark failed" onClick={() => void reconcile(item, "failed")} className="text-red-600"><XCircle size={18} /></button></div>}</td></tr>)}</tbody></table>{loading && <p className="p-8 text-center text-sm text-slate-500">Loading payment intents...</p>}{!loading && !filtered.length && <p className="p-8 text-center text-sm text-slate-500">No payment intents match this filter.</p>}</section></div>;
}
