import { useEffect, useState } from "react";
import { Banknote, CheckCircle2, CircleDollarSign } from "lucide-react";
import { useAuth } from "../../contexts/AuthContext";
import { fetchStaffFinance, recordStaffLoanRepayment, type StaffLoan } from "../../services/StaffFinanceService";

export default function StaffLoanRepaymentsPage() {
  const { user } = useAuth(); const [loans, setLoans] = useState<StaffLoan[]>([]); const [amounts, setAmounts] = useState<Record<string, string>>({}); const [message, setMessage] = useState("");
  const load = async () => setLoans((await fetchStaffFinance()).loans.filter((loan) => loan.status === "active" && loan.balance > 0)); useEffect(() => { void load(); }, []);
  const save = async (loan: StaffLoan) => { const amount = Number(amounts[loan.id]); if (!user?.uid || !amount) return setMessage("Enter a valid repayment amount."); try { await recordStaffLoanRepayment(loan, amount, user.uid); setMessage(`Repayment recorded for ${loan.staffName}.`); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to record repayment."); } };
  const total = loans.reduce((sum, loan) => sum + loan.balance, 0);
  return <main className="min-h-screen bg-slate-50 p-4 md:p-8"><div className="mx-auto max-w-6xl space-y-6"><header><p className="text-sm font-semibold uppercase tracking-wider text-indigo-600">Staff finance</p><h1 className="mt-1 text-3xl font-bold text-slate-900">Loan repayments</h1><p className="mt-1 text-sm text-slate-500">Record installments and maintain an accurate outstanding balance for every staff loan.</p></header>{message && <div className="rounded-lg border border-indigo-100 bg-indigo-50 px-4 py-3 text-sm text-indigo-800">{message}</div>}<div className="grid gap-4 sm:grid-cols-3"><Metric icon={<Banknote />} label="Active loans" value={loans.length} /><Metric icon={<CircleDollarSign />} label="Outstanding balance" value={`GHS ${total.toFixed(2)}`} /><Metric icon={<CheckCircle2 />} label="Control status" value="Audited" /></div><section className="divide-y divide-slate-100 rounded-xl border border-slate-200 bg-white">{loans.map((loan) => <div key={loan.id} className="flex flex-col gap-4 p-5 md:flex-row md:items-center md:justify-between"><div><p className="font-semibold text-slate-900">{loan.staffName}</p><p className="mt-1 text-sm text-slate-500">{loan.purpose || "Staff loan"} · Installment GHS {loan.installment.toFixed(2)}</p><p className="mt-2 text-sm font-bold text-amber-700">Remaining: GHS {loan.balance.toFixed(2)}</p></div><div className="flex gap-2"><input className="w-40 rounded-lg border border-slate-200 px-3 py-2 text-sm outline-none focus:border-indigo-500" type="number" min="0.01" max={loan.balance} placeholder="Amount" value={amounts[loan.id] || ""} onChange={(e) => setAmounts({ ...amounts, [loan.id]: e.target.value })} /><button onClick={() => void save(loan)} className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white hover:bg-indigo-700">Record</button></div></div>)}{!loans.length && <p className="p-10 text-center text-sm text-slate-500">No active staff loans require repayment.</p>}</section></div></main>;
}
function Metric({ icon, label, value }: { icon: React.ReactNode; label: string; value: string | number }) { return <div className="surface surface-hover border-primary/20 p-5"><div className="text-primary">{icon}</div><p className="mt-3 text-2xl font-black text-dark">{value}</p><p className="text-sm text-slate-500">{label}</p></div>; }
