import { useEffect, useState } from "react";
import { Save } from "lucide-react";
import { useAuth } from "../../contexts/AuthContext";
import { fetchStudents } from "../../services/StudentService";
import { saveTermComments, fetchTermComments } from "../../services/TermCommentsService";
import { interestOptions, remarkOptions } from "../../services/ReportCommentLibrary";

const currentYear = () => { const year = new Date().getFullYear(); return `${year}/${year + 1}`; };
export default function TermCommentsPage() { const { user } = useAuth(); const [students, setStudents] = useState<any[]>([]); const [studentId, setStudentId] = useState(""); const [academicYear, setAcademicYear] = useState(currentYear()); const [term, setTerm] = useState("Term 1"); const [interests, setInterests] = useState(""); const [conductRemark, setConductRemark] = useState(""); const [attendanceRemark, setAttendanceRemark] = useState(""); const [nextSteps, setNextSteps] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { void fetchStudents().then(setStudents).catch(e => setError(e instanceof Error ? e.message : "Unable to load students.")); }, []);
  useEffect(() => { if (!studentId || !academicYear || !term) return; void fetchTermComments(studentId, academicYear, term).then(item => { setInterests(item?.interests || ""); setConductRemark(item?.conductRemark || ""); setAttendanceRemark(item?.attendanceRemark || ""); setNextSteps(item?.nextSteps || ""); }).catch(e => setError(e instanceof Error ? e.message : "Unable to load comments.")); }, [academicYear, studentId, term]);
  const save = async () => { if (!user || !studentId || !academicYear.trim()) return setError("Select a student and provide an academic year."); setSaving(true); setError(""); try { await saveTermComments({ studentId, academicYear: academicYear.trim(), term, interests: interests.trim(), conductRemark: conductRemark.trim(), attendanceRemark: attendanceRemark.trim(), nextSteps: nextSteps.trim(), updatedBy: user.uid }); setMessage("End-of-term comments saved."); } catch (e) { setError(e instanceof Error ? e.message : "Unable to save comments."); } finally { setSaving(false); } };
  return <div className="mx-auto max-w-4xl space-y-6"><div><p className="text-sm font-semibold uppercase tracking-wider text-indigo-600">End-of-term preparation</p><h1 className="mt-1 text-3xl font-bold text-slate-900">Student comments</h1><p className="mt-2 text-sm text-slate-500">Choose from the professional comment library or enter a tailored comment.</p></div>{message && <div className="rounded-lg bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{message}</div>}{error && <div className="rounded-lg bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}<section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="grid gap-4 md:grid-cols-3"><label className="text-sm font-semibold text-slate-700 md:col-span-3">Student<select value={studentId} onChange={e => setStudentId(e.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2.5"><option value="">Select student</option>{students.map(student => <option key={student.studentId || student.id} value={student.studentId || student.id}>{student.displayName || student.name || student.studentName} · {student.classId || "No class"}</option>)}</select></label><label className="text-sm font-semibold text-slate-700">Academic year<input value={academicYear} onChange={e => setAcademicYear(e.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2.5" /></label><label className="text-sm font-semibold text-slate-700">Term<select value={term} onChange={e => setTerm(e.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2.5"><option>Term 1</option><option>Term 2</option><option>Term 3</option></select></label></div><div className="mt-5 grid gap-4 md:grid-cols-2"><TextArea label="Interests and strengths" value={interests} onChange={setInterests} placeholder="Choose an interest" options={interestOptions} /><TextArea label="Conduct remark" value={conductRemark} onChange={setConductRemark} placeholder="Choose a remark" options={remarkOptions} /><TextArea label="Attendance remark" value={attendanceRemark} onChange={setAttendanceRemark} placeholder="Attendance and punctuality summary" /><TextArea label="Next steps / recommendation" value={nextSteps} onChange={setNextSteps} placeholder="Recommended support or next-term target" /></div><button disabled={saving || !studentId} onClick={() => void save()} className="mt-5 flex items-center gap-2 rounded-lg bg-indigo-600 px-4 py-2.5 font-semibold text-white disabled:opacity-50"><Save size={16} />{saving ? "Saving..." : "Save comments"}</button></section></div>; }
function TextArea({ label, value, onChange, placeholder, options }: { label: string; value: string; onChange: (value: string) => void; placeholder: string; options?: string[] }) { return <label className="text-sm font-semibold text-slate-700">{label}{options && <select value={value} onChange={e => onChange(e.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2.5 font-normal"><option value="">{placeholder}</option>{options.map(option => <option key={option} value={option}>{option}</option>)}</select>}<textarea value={value} onChange={e => onChange(e.target.value)} placeholder={options ? "Optional tailored wording" : placeholder} rows={options ? 2 : 4} className="mt-1 w-full resize-y rounded-lg border border-slate-300 px-3 py-2.5 font-normal" /></label>; }
