import { collection, getDocs } from "firebase/firestore";
import { db } from "../firebaseConfig";
import { missingRequiredSubjects } from "./SubjectSetupService";
import { approvalId } from "./ReportApprovalService";

export type ReportReadinessRow = { studentId: string; studentName: string; classId: string; missingSubjects: string[]; missingScores: string[]; commentsComplete: boolean; approved: boolean; ready: boolean };
export async function fetchEndOfTermReadiness(academicYear: string, term: string): Promise<ReportReadinessRow[]> {
  const [students, grades, setups, comments, approvals] = await Promise.all([getDocs(collection(db, "students")), getDocs(collection(db, "grades")), getDocs(collection(db, "classSubjects")), getDocs(collection(db, "termComments")), getDocs(collection(db, "reportApprovals"))]);
  const subjectMap = new Map(setups.docs.map(item => [item.id, (item.data().subjects as string[]) || []])); const gradeMap = new Map<string, any[]>(); grades.docs.forEach(item => { const data = item.data(); if (String(data.academicYear || "") !== academicYear || String(data.term || "") !== term) return; const id = String(data.studentId || ""); gradeMap.set(id, [...(gradeMap.get(id) || []), data]); }); const commentsSet = new Set(comments.docs.filter(item => String(item.data().academicYear || "") === academicYear && String(item.data().term || "") === term).map(item => String(item.data().studentId || ""))); const approvalsSet = new Set(approvals.docs.filter(item => String(item.data().academicYear || "") === academicYear && String(item.data().term || "") === term && item.data().status === "approved").map(item => item.id));
  return students.docs.map(item => { const data = item.data(); const studentId = String(data.studentId || item.id); const recorded = gradeMap.get(studentId) || []; const required = subjectMap.get(String(data.classId || "")) || []; const recordedSubjects = recorded.map(grade => String(grade.subject || grade.subjectName || "")); const missingSubjects = missingRequiredSubjects(required, recordedSubjects); const missingScores = recorded.filter(grade => !Number.isFinite(Number(grade.finalScore ?? grade.mark ?? grade.score))).map(grade => String(grade.subject || grade.subjectName || "Unknown subject")); const commentsComplete = commentsSet.has(studentId); const approved = approvalsSet.has(approvalId(studentId, academicYear, term)); const ready = required.length > 0 && !missingSubjects.length && !missingScores.length && commentsComplete && approved; return { studentId, studentName: String(data.displayName || data.studentName || data.name || studentId), classId: String(data.classId || ""), missingSubjects, missingScores, commentsComplete, approved, ready }; }).filter(row => row.classId);
}
