export type QuizDraft = { assignmentId: string; studentId: string; responses: Record<number, string>; essayText: string; savedAt: string };
const databaseName = "giitech-ssm-offline"; const storeName = "quizDrafts";
function openDatabase() { return new Promise<IDBDatabase>((resolve, reject) => { const request = indexedDB.open(databaseName, 2); request.onupgradeneeded = () => { if (!request.result.objectStoreNames.contains(storeName)) request.result.createObjectStore(storeName, { keyPath: "key" }); }; request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); }
const keyFor = (assignmentId: string, studentId: string) => `${studentId}_${assignmentId}`;
export async function saveQuizDraft(draft: QuizDraft) { if (!("indexedDB" in window)) return; const database = await openDatabase(); database.transaction(storeName, "readwrite").objectStore(storeName).put({ ...draft, key: keyFor(draft.assignmentId, draft.studentId) }); }
export async function getQuizDraft(assignmentId: string, studentId: string) { if (!("indexedDB" in window)) return null; const database = await openDatabase(); return new Promise<QuizDraft | null>((resolve, reject) => { const request = database.transaction(storeName, "readonly").objectStore(storeName).get(keyFor(assignmentId, studentId)); request.onsuccess = () => resolve(request.result as QuizDraft | null); request.onerror = () => reject(request.error); }); }
export async function queueQuizSubmission(data: Record<string, unknown>) { if (!("indexedDB" in window)) return; const database = await openDatabase(); database.transaction(storeName, "readwrite").objectStore(storeName).put({ key: `submission_${Date.now()}`, queuedSubmission: data, savedAt: new Date().toISOString() }); }
export async function getQueuedQuizSubmissions() { if (!("indexedDB" in window)) return []; const database = await openDatabase(); return new Promise<Array<{ key: string; queuedSubmission: Record<string, unknown> }>>((resolve, reject) => { const request = database.transaction(storeName, "readonly").objectStore(storeName).getAll(); request.onsuccess = () => resolve((request.result as Array<{ key: string; queuedSubmission?: Record<string, unknown> }>).filter(item => item.queuedSubmission) as Array<{ key: string; queuedSubmission: Record<string, unknown> }>); request.onerror = () => reject(request.error); }); }
export async function removeQueuedQuizSubmission(key: string) { const database = await openDatabase(); database.transaction(storeName, "readwrite").objectStore(storeName).delete(key); }
