import { doc, getDoc, serverTimestamp, setDoc } from "firebase/firestore";
import { getAuth } from "firebase/auth";
import { db } from "../firebaseConfig";

export function studentIdentityPayload(studentId: string) { return JSON.stringify({ app: "giitech-ssm", type: "student-identity", version: 1, studentId }); }
export function staffIdentityPayload(staffId: string, userId?: string) { return JSON.stringify({ app: "giitech-ssm", type: "staff-identity", version: 1, staffId, userId: userId || "" }); }
export function parseStudentIdentity(value: string) { const raw = value.trim(); if (!raw) throw new Error("Scan or enter a student QR value."); try { const parsed = JSON.parse(raw) as { app?: string; type?: string; studentId?: string }; if (parsed.app !== "giitech-ssm" || parsed.type !== "student-identity" || !parsed.studentId) throw new Error("This QR code is not an ASTEM-SSM student identity."); return parsed.studentId; } catch (error) { if (error instanceof SyntaxError) return raw; throw error; } }
export async function findStudentForQr(studentId: string) { const snapshot = await getDoc(doc(db, "students", studentId)); if (!snapshot.exists()) throw new Error("No student record matches this identity."); return { id: snapshot.id, ...snapshot.data() } as { id: string; studentId?: string; displayName?: string; classId?: string; status?: string }; }
export async function recordQrAttendance(student: { id: string; studentId?: string; displayName?: string; classId?: string }, status: "Present" | "Absent" = "Present") { const date = new Date().toISOString().slice(0, 10); const studentId = student.studentId || student.id; const currentUser = getAuth().currentUser; const role = (await getDoc(doc(db, "users", currentUser?.uid || ""))).data()?.role; await setDoc(doc(db, "attendance", `qr_${studentId}_${date}`), { studentId, studentName: student.displayName || studentId, classId: student.classId || "", date, status, present: status === "Present", method: "qr", recordedBy: currentUser?.uid || "", ...(role === "teacher" ? { teacherId: currentUser?.uid } : {}), updatedAt: serverTimestamp() }, { merge: true }); }
