import { collection, getDocs } from "firebase/firestore";
import { db } from "../firebaseConfig";
import { calculateFinalScore, getGradingConfiguration } from "./GradingConfigurationService";

export type RankingRow = { studentId: string; studentName: string; classId: string; streamId: string; departmentId: string; subjectAverages: Record<string, number>; overallAverage: number; rank: number };
export async function calculateRankings(filters: { subject?: string; classId?: string; streamId?: string; departmentId?: string; academicYear?: string; term?: string } = {}) {
  const [studentSnapshot, gradeSnapshot, gradingConfiguration] = await Promise.all([getDocs(collection(db, "students")), getDocs(collection(db, "grades")), getGradingConfiguration()]);
  const profiles = new Map<string, { name: string; classId: string; streamId: string; departmentId: string }>();
  studentSnapshot.docs.forEach(item => { const data = item.data(); const id = String(data.studentId || item.id); profiles.set(id, { name: String(data.displayName || data.studentName || id), classId: String(data.classId || ""), streamId: String(data.streamId || data.stream || ""), departmentId: String(data.departmentId || data.department || "") }); });
  const scores = new Map<string, Map<string, number[]>>();
  gradeSnapshot.docs.forEach(item => { const data = item.data(); const studentId = String(data.studentId || ""); const subject = String(data.subject || data.subjectName || "General"); const mark = data.finalScore != null ? Number(data.finalScore) : calculateFinalScore(data.classScore == null ? undefined : Number(data.classScore), data.examScore == null ? undefined : Number(data.examScore), gradingConfiguration); const profile = profiles.get(studentId); if (!studentId || !profile || !Number.isFinite(mark) || (filters.academicYear && String(data.academicYear || "") !== filters.academicYear) || (filters.term && String(data.term || "") !== filters.term) || (filters.classId && profile.classId !== filters.classId) || (filters.streamId && profile.streamId !== filters.streamId) || (filters.departmentId && profile.departmentId !== filters.departmentId) || (filters.subject && subject !== filters.subject)) return; const bySubject = scores.get(studentId) || new Map<string, number[]>(); bySubject.set(subject, [...(bySubject.get(subject) || []), mark]); scores.set(studentId, bySubject); });
  const rows = [...scores.entries()].map(([studentId, subjects]) => { const subjectAverages = Object.fromEntries([...subjects.entries()].map(([subject, values]) => [subject, values.reduce((sum, value) => sum + value, 0) / values.length])); const values = Object.values(subjectAverages); return { studentId, studentName: profiles.get(studentId)?.name || studentId, classId: profiles.get(studentId)?.classId || "", streamId: profiles.get(studentId)?.streamId || "", departmentId: profiles.get(studentId)?.departmentId || "", subjectAverages, overallAverage: values.reduce((sum, value) => sum + value, 0) / (values.length || 1), rank: 0 }; }).sort((a, b) => b.overallAverage - a.overallAverage);
  let lastScore = -1; let lastRank = 0; rows.forEach((row, index) => { if (row.overallAverage !== lastScore) lastRank = index + 1; row.rank = lastRank; lastScore = row.overallAverage; }); return rows;
}
