import { useEffect, useMemo, useState } from "react";
import { Banknote, Printer, ReceiptText, WalletCards } from "lucide-react";
import jsPDF from "jspdf";
import { useAuth } from "../../contexts/AuthContext";
import { getParentProfileByUserId } from "../../services/ParentService";
import { createMobileMoneyIntent, type MobileMoneyProvider } from "../../services/MobileMoneyService";
import {
  buildLedgerSummaries,
  fetchFeePaymentsByStudentIds,
  fetchStudentChargesByStudentIds,
  type FeePayment,
  type StudentCharge,
} from "../../services/FinanceService";

const currency = (value: number) => new Intl.NumberFormat("en-GH", { style: "currency", currency: "GHS" }).format(value || 0);

export default function ParentFeesPage() {
  const { user } = useAuth();
  const [charges, setCharges] = useState<StudentCharge[]>([]);
  const [payments, setPayments] = useState<FeePayment[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [paymentForm, setPaymentForm] = useState({ studentId: "", amount: "", phone: "", provider: "mtn-momo" as MobileMoneyProvider });
  const [paymentMessage, setPaymentMessage] = useState("");
  const [paying, setPaying] = useState(false);

  useEffect(() => {
    if (!user) return;
    const loadFees = async () => {
      try {
        const parent = await getParentProfileByUserId(user.uid);
        const studentIds = parent?.studentIds || [];
        const [linkedCharges, linkedPayments] = await Promise.all([
          fetchStudentChargesByStudentIds(studentIds),
          fetchFeePaymentsByStudentIds(studentIds),
        ]);
        setCharges(linkedCharges);
        setPayments(linkedPayments);
        setPaymentForm(current => ({ ...current, studentId: studentIds[0] || "" }));
      } catch (loadError) {
        console.error(loadError);
        setError("Unable to load fee information.");
      } finally {
        setLoading(false);
      }
    };
    loadFees();
  }, [user]);

  const summaries = useMemo(() => buildLedgerSummaries(charges, payments), [charges, payments]);

  const startPayment = async (event: React.FormEvent) => { event.preventDefault(); setPaying(true); setError(""); setPaymentMessage(""); try { const result = await createMobileMoneyIntent({ amount: Number(paymentForm.amount), studentId: paymentForm.studentId, provider: paymentForm.provider, phone: paymentForm.phone.trim() }); setPaymentMessage(`${result.message} Reference: ${result.intentId}`); setPaymentForm(current => ({ ...current, amount: "", phone: "" })); } catch (paymentError) { setError(paymentError instanceof Error ? paymentError.message : "Unable to start Mobile Money payment."); } finally { setPaying(false); } };

  const printReceipt = (payment: FeePayment) => {
    const doc = new jsPDF();
    doc.setFontSize(18); doc.text("ASTEM Smart School Manager", 14, 18);
    doc.setFontSize(13); doc.text("Fee Payment Receipt", 14, 29);
    doc.setFontSize(10);
    const rows = [
      ["Receipt", payment.receiptNumber], ["Student", `${payment.studentName} (${payment.studentId})`],
      ["Academic Year", payment.academicYear], ["Term", payment.term], ["Payment Method", payment.paymentMethod],
      ["Reference", payment.reference || "-"], ["Amount Paid", currency(payment.amount)], ["Notes", payment.notes || "-"],
    ];
    rows.forEach(([label, value], index) => doc.text(`${label}: ${value}`, 14, 44 + index * 8));
    doc.text("Generated by ASTEM", 14, 116);
    doc.save(`${payment.receiptNumber}.pdf`);
  };

  if (loading) return <p className="py-10 text-center text-sm text-gray-500">Loading fees...</p>;

  return (
    <div className="space-y-5">
      <div><h1 className="text-2xl font-bold text-gray-900">Fees and Payments</h1><p className="mt-1 text-sm text-gray-600">View ward balances, charges, and payment receipts.</p></div>
      {error && <p className="rounded-md bg-red-50 px-3 py-2 text-sm text-red-700">{error}</p>}
      {paymentMessage && <p className="rounded-md bg-indigo-50 px-3 py-2 text-sm text-indigo-700">{paymentMessage}</p>}
      <div className="grid gap-3 sm:grid-cols-3">
        <Summary icon={<WalletCards size={18} />} label="Total Charged" value={currency(summaries.reduce((sum, item) => sum + item.charged, 0))} />
        <Summary icon={<Banknote size={18} />} label="Total Paid" value={currency(summaries.reduce((sum, item) => sum + item.paid, 0))} />
        <Summary icon={<ReceiptText size={18} />} label="Outstanding" value={currency(summaries.reduce((sum, item) => sum + item.balance, 0))} />
      </div>
      <div className="grid gap-5 xl:grid-cols-2">
        <section className="border bg-white"><h2 className="border-b px-4 py-3 font-semibold">Ward Balances</h2><div className="divide-y">{summaries.map((item) => <div key={item.studentId} className="flex items-center justify-between gap-3 px-4 py-3"><div><p className="font-medium">{item.studentName}</p><p className="text-xs text-gray-500">{item.studentId}</p></div><div className="text-right text-sm"><p>Paid: <span className="text-green-700">{currency(item.paid)}</span></p><p>Balance: <span className="font-semibold text-red-700">{currency(item.balance)}</span></p></div></div>)}{!summaries.length && <Empty />}</div></section>
        <section className="border bg-white"><h2 className="border-b px-4 py-3 font-semibold">Payment History</h2><div className="divide-y">{payments.map((item) => <div key={item.id} className="flex items-center justify-between gap-3 px-4 py-3"><div><p className="font-medium">{item.receiptNumber}</p><p className="text-xs text-gray-500">{item.studentName} | {item.term} | {item.paymentMethod}</p></div><div className="flex items-center gap-2"><p className="font-semibold">{currency(item.amount)}</p><button title="Download receipt" onClick={() => printReceipt(item)} className="rounded-md p-2 text-indigo-600 hover:bg-indigo-50"><Printer size={16} /></button></div></div>)}{!payments.length && <Empty />}</div></section>
      </div>
      <form onSubmit={startPayment} className="grid gap-3 border border-indigo-100 bg-indigo-50/50 p-5 md:grid-cols-5"><div className="md:col-span-5"><h2 className="font-semibold text-slate-900">Pay by Mobile Money</h2><p className="mt-1 text-xs text-slate-500">Create a secure payment request for a linked student.</p></div><select required value={paymentForm.studentId} onChange={e => setPaymentForm({ ...paymentForm, studentId: e.target.value })} className="rounded-md border bg-white px-3 py-2 text-sm"><option value="">Select student</option>{summaries.map(item => <option key={item.studentId} value={item.studentId}>{item.studentName}</option>)}</select><input required min="0.01" step="0.01" type="number" placeholder="Amount (GHS)" value={paymentForm.amount} onChange={e => setPaymentForm({ ...paymentForm, amount: e.target.value })} className="rounded-md border px-3 py-2 text-sm" /><input required placeholder="Mobile number" value={paymentForm.phone} onChange={e => setPaymentForm({ ...paymentForm, phone: e.target.value })} className="rounded-md border px-3 py-2 text-sm" /><select value={paymentForm.provider} onChange={e => setPaymentForm({ ...paymentForm, provider: e.target.value as MobileMoneyProvider })} className="rounded-md border bg-white px-3 py-2 text-sm"><option value="mtn-momo">MTN MoMo</option><option value="telecel-cash">Telecel Cash</option><option value="airteltigo-money">AirtelTigo Money</option></select><button disabled={paying} className="w-fit justify-self-start whitespace-nowrap rounded-md bg-indigo-600 px-3 py-2 text-sm font-medium text-white disabled:opacity-60">{paying ? "Starting..." : "Start payment"}</button></form>
      <section className="border bg-white"><h2 className="border-b px-4 py-3 font-semibold">Charge History</h2><div className="divide-y">{charges.map((item) => <div key={item.id} className="flex items-center justify-between gap-3 px-4 py-3"><div><p className="font-medium">{item.description}</p><p className="text-xs text-gray-500">{item.studentName} | {item.term} | {item.academicYear}</p></div><p className="font-semibold">{currency(item.amount)}</p></div>)}{!charges.length && <Empty />}</div></section>
    </div>
  );
}

function Summary({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="border bg-white p-4"><div className="flex items-center gap-2 text-gray-500">{icon}<span className="text-xs uppercase">{label}</span></div><p className="mt-2 text-xl font-bold text-gray-900">{value}</p></div>; }
function Empty() { return <p className="px-4 py-6 text-sm text-gray-500">No records yet.</p>; }
